### ISSUE TITLE
Mutations do not work with the MockProvider

### ISSUE THREAD

**Issue by Myrmod** [apollographql/apollo-client#10110]
Hello,

I'm trying to update an address by calling a mutation query. This however results in a normal get query being called as I guess. I cannot tell why this happens and it seems to me like a bug.

**Intended outcome:**
I want to run the following query:
```ts
export const UPDATE_CUSTOMER_ADDRESS = gql`
  mutation UpdateCustomerAddress($id: String!, $input: CustomerAddressInput!) {
    updateCustomerAddress(id: $id, input: $input) {
      id
    }
  }
`;
```

**Actual outcome:**
Error message in the console:
```
Uncaught (in promise) Error: No more mocked responses for the query: {
  customer {
    firstname
    lastname
    addresses {
      id
      firstname
      lastname
      postcode
      street
      city
      country_code
      telephone
      default_shipping
    }
  }
}
Expected variables: {}

    at new ApolloError2 (index.ts:71:5)
    at QueryManager.ts:1080:13
    at both (asyncMap.ts:30:30)
    at asyncMap.ts:19:47
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:16)
    at Object.error (asyncMap.ts:31:39)
    at notifySubscription (module.js:137:18)
    at onNotify (module.js:176:3)
    at SubscriptionObserver2.error (module.js:229:5)
```

**How to reproduce the issue:**
I made a repository for reproduction: https://github.com/Myrmod/mockprovider-mutation-request

**Versions**
```
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9 
    @apollo/react-testing: ^4.0.0 => 4.0.0
```

best regards

EDIT:
I think I just found the cause:
```ts
// https://github.com/Myrmod/mockprovider-mutation-request/blob/master/src/AddressBook/modules/AddressList/AddressItem.tsx#L31

const [updateAddress, { loading: updateLoading, error: updateError }] =
    useMutation(UPDATE_CUSTOMER_ADDRESS, {
      refetchQueries: [{ query: GET_CUSTOMER }], // here
      awaitRefetchQueries: true,
    });
```

How do I integrate this into the mocks for the `MockProvider`?

**Comment by Myrmod** [comment]
It seems I misunderstood how to work with the `mocks` array.

When testing the `mocks` array have to match the order in which you make your changes. So in my case since I have:
1. GET_CUSTOMER 
2. UPDATE_CUSTOMER_ADDRESS
3. GET_CUSTOMER 

My `mocks` have to be structured the same way. So I need a mock for all 3 of those request above. The a mock, once used, won't be used again.
