### ISSUE TITLE
ApolloError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by DomVournias** [apollographql/apollo-client#10430]
I am getting this error: 

`(node:4356) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
error - ApolloError: Cannot read properties of undefined (reading 'name')
    at new ApolloError (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\errors\errors.cjs:34:28)     
    at C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\core\core.cjs:1800:19
    at both (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:997:53)
    at C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:990:72
    at new Promise (<anonymous>)
    at Object.then (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:990:24)  
    at Object.error (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:998:49) 
    at notifySubscription (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\zen-observable\lib\Observable.js:140:18) 
    at onNotify (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\zen-observable\lib\Observable.js:240:7) {
  graphQLErrors: [],
  clientErrors: [],
  networkError: TypeError: Cannot read properties of undefined (reading 'name')
      at new Request (node:internal/deps/undici/undici:4977:35) 
      at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
      at Object.fetch (node:internal/deps/undici/undici:6370:20)
      at fetch (node:internal/bootstrap/pre_execution:196:25)   
      at C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\link\http\http.cjs:567:13
      at new Subscription (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\zen-observable\lib\Observable.js:197:34) 
      at Observable.subscribe (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\zen-observable\lib\Observable.js:279:14)
      at Object.complete (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:1109:43)
      at Concast.start (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:1136:23)
      at new Concast (C:\Users\kiria\Desktop\GEON\geonhellas.gr\geon\node_modules\@apollo\client\utilities\utilities.cjs:1128:19),
  extraInfo: undefined,
  page: '/'
}`

Debug steps:

Reinstalled node modules
Reinstalled @apollo/client
Disabled all queries - not a query typo or bug

Nothing worked so far, this bug doesn't give any directions...It's really confusing.

**Comment by DomVournias** [comment]
Solved by upgrading to the latest Node version.
