### ISSUE TITLE
Building react app with with vite while using apollo/client causes could not resolve window.js

### ISSUE THREAD

**Issue by PawelTechtailor** [apollographql/apollo-client#10445]
Hi,

got question about error I received and can't figure out why:

```
Could not resolve "./window.js" from "../../node_modules/.pnpm/@apollo+client@3.7.4_35fe8cfd9a0d0e954e7889a0f9ef851b/node_modules/@apollo/client/utilities/globals/index.js"
file: /home/smolka/Job/someapp/node_modules/.pnpm/@apollo+client@3.7.4_35fe8cfd9a0d0e954e7889a0f9ef851b/node_modules/@apollo/client/utilities/globals/index.js
error during build:
RollupError: Could not resolve "./window.js" from "../../node_modules/.pnpm/@apollo+client@3.7.4_35fe8cfd9a0d0e954e7889a0f9ef851b/node_modules/@apollo/client/utilities/globals/index.js"
    at error (file:///home/smolka/Job/someapp/node_modules/.pnpm/rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:2041:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/smolka/Job/someapp/node_modules/.pnpm/rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:23137:24)
    at file:///home/smolka/Job/someapp/node_modules/.pnpm/rollup@3.10.0/node_modules/rollup/dist/es/shared/rollup.js:23099:26
 ELIFECYCLE  Command failed with exit code 1.
```

it happens when I do `vite build` ( on vite react-ts template). I am using apollo/client 3.7.4

I would be very thanksful for any suggestions / ideas where to look for.

**Comment by bignimbus** [comment]
Hi @PawelTechtailor 👋🏻  did @daegren's suggestion address your issue?  (Also: thanks @daegren!)

**Comment by ioveracker** [comment]
In my app, I needed `global` to be defined for another library, so I removed `define: { global: 'window' }` and added it to a new script tag in the `index.html`. This does not cause the apollo build error but makes `global` available at runtime for libraries that may depend on it.

```
<script>
var global = global || window
</script>
```
