### ISSUE TITLE
CurrentFetch is not a function in Docker

### ISSUE THREAD

**Issue by GreenJ84** [apollographql/apollo-client#10725]
### Issue Description

When running a docker container with my Express Typescript app I am having problems using Apollo client to query GraphQL endpoints. I recieve the error 

```ResponseError: An error occurred while retrieving data from the external LeetCode API
    at /app/src/leetcode/query.ts:45:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  error: ApolloError: currentFetch is not a function
      at new ApolloError (/app/node_modules/@apollo/client/errors/index.js:29:28)
      at /app/node_modules/@apollo/client/core/QueryManager.js:657:19
      at both (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53)
      at /app/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
      at new Promise (<anonymous>)
      at Object.then (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24)
      at Object.error (/app/node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49)
      at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (/app/node_modules/zen-observable/lib/Observable.js:240:7) {
    graphQLErrors: [],
    clientErrors: [],
    networkError: TypeError: currentFetch is not a function
        at /app/node_modules/@apollo/client/link/http/createHttpLink.js:100:13
        at new Subscription (/app/node_modules/zen-observable/lib/Observable.js:197:34)
        at Observable.subscribe (/app/node_modules/zen-observable/lib/Observable.js:279:14)
        at Object.complete (/app/node_modules/@apollo/client/utilities/observables/Concast.js:62:43)
        at Concast.start (/app/node_modules/@apollo/client/utilities/observables/Concast.js:89:23)
        at new Concast (/app/node_modules/@apollo/client/utilities/observables/Concast.js:81:19)
        at QueryManager.getObservableFromLink (/app/node_modules/@apollo/client/core/QueryManager.js:592:35)
        at QueryManager.getResultsFromLink (/app/node_modules/@apollo/client/core/QueryManager.js:632:30)
        at resultsFromLink (/app/node_modules/@apollo/client/core/QueryManager.js:809:58)
        at QueryManager.fetchQueryByPolicy (/app/node_modules/@apollo/client/core/QueryManager.js:835:21),
    extraInfo: undefined
  },
  error_code: 502
}
```

### Link to Reproduction

https://github.com/GreenJ84/github-readme-streak-typescript

**Comment by bignimbus** [comment]
Hi @GreenJ84 👋🏻  thanks for opening this issue!  This line in your repo stood out to me:

https://github.com/GreenJ84/github-readme-streak-typescript/blob/b167f7cae45cbedd0a35e37f3a5c21f4209d7f16/src/leetcode/query.ts#L17

Looking the project's `package.json`, it appears that `fetch` is being `require`d from https://github.com/andris9/fetch.  That library's default export is an object, not a function, so it wouldn't be able to be used by Apollo Client to wrap network requests.  One standard approach is to use the default [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) function in JavaScript instead.  I'll close this issue for now; please do feel free to join our [Discord](https://discord.gg/graphos) or [community forum](https://community.apollographql.com), both of which are great for Q&A!
