### ISSUE TITLE
NextJS Build Crash: useSuspenseQuery crashes the build process of NextJS

### ISSUE THREAD

**Issue by IvaanTorres** [apollographql/apollo-client#11038]
I am trying to use Apollo plus NEXT.JS 13 (/app mode). I decided to use the experimental features of Apollo to make possible the use of Apollo on server components and so, share the state between server and client side.

During the dev server, everything works as expected. However, when I run the build process of NEXT.JS, it crashes because of the use of "useSuspenseQuery" (below the error). In case of change to "useQuery", it builds perfectly.

### Error thrown by NEXT.JS 13:
```
[=   ] - info Generating static pages (3/4)ApolloError: Response not successful: Received status code 500
    at new ApolloError (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:44297:28)
    at /Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:43756:19
    at both (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48039:53)
    at /Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48032:72
    at new Promise (<anonymous>)
    at Object.then (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48032:24)
    at Object.error (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48040:49)
    at notifySubscription (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38864:18)
    at onNotify (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38903:3)
    at SubscriptionObserver.error (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38964:7) {
  graphQLErrors: [],
  protocolErrors: [],
  clientErrors: [],
  networkError: Error [ServerError]: Response not successful: Received status code 500
      at Object.throwServerError (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:45118:17)
      at parseJsonBody (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:44716:15)
      at /Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:44752:48
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 500,
    result: ''
  },
  extraInfo: undefined
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
ApolloError: Response not successful: Received status code 500
    at new ApolloError (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:44297:28)
    at /Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:43756:19
    at both (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48039:53)
    at /Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48032:72
    at new Promise (<anonymous>)
    at Object.then (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48032:24)
    at Object.error (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:48040:49)
    at notifySubscription (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38864:18)
    at onNotify (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38903:3)
    at SubscriptionObserver.error (/Users/itorres/Projects/ecommerce-dxp/ui/.next/server/chunks/643.js:38964:7)
- info Generating static pages (4/4)

> Export encountered errors on following paths:
        /page: /
```

#### Client.js (Client which I import to every server component. It works fine):
```ts
/* eslint-disable import/no-unresolved */
import { ApolloClient, HttpLink, InMemoryCache } from '@apollo/client'
import { registerApolloClient } from '@apollo/experimental-nextjs-app-support/rsc'

export const { getClient } = registerApolloClient(() => new ApolloClient({
  cache: new InMemoryCache(),
  link: new HttpLink({
    // Since we're using SSR, we need to provide the full URL (localhost can't be resolved)
    uri: 'http://127.0.0.1:8000/graphql',
  }),
}))

```

#### Apollo Provider which is used inside the root page.ts to wrap all the content:
```ts
'use client'

/* eslint-disable import/no-unresolved */

/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable react/jsx-filename-extension */
import {
  ApolloClient,
  ApolloLink,
  HttpLink,
  SuspenseCache,
} from '@apollo/client'
import {
  NextSSRApolloClient,
  ApolloNextAppProvider,
  NextSSRInMemoryCache,
  SSRMultipartLink,
} from '@apollo/experimental-nextjs-app-support/ssr'
import env from '../shared/enums/config/environment'

function makeSuspenseCache() {
  return new SuspenseCache()
}

function makeClient() {
  const httpLink = new HttpLink({
    // https://studio.apollographql.com/public/spacex-l4uc6p/
    uri: env.NEXT_PUBLIC_API_URL,
  })

  return new NextSSRApolloClient({
    cache: new NextSSRInMemoryCache(),
    link:
      typeof window === 'undefined'
        ? ApolloLink.from([
          new SSRMultipartLink({
            stripDefer: true,
          }),
          httpLink,
        ])
        : httpLink,
  })
}

const ApolloWrapper = ({ children }) => (
  <ApolloNextAppProvider
    makeClient={makeClient}
    makeSuspenseCache={makeSuspenseCache}
  >
    {children}
  </ApolloNextAppProvider>
)

export default ApolloWrapper

```

#### Root page:
```ts
/* eslint-disable react/react-in-jsx-scope */
// import './globals.css'
import { Inter } from 'next/font/google'
import ApolloWrapper from '../lib/apollo-wrapper'
import ProvidersWrapper from '../lib/providers-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body className={inter.className}>
      <ApolloWrapper>
        <ProvidersWrapper>
          {children}
        </ProvidersWrapper>
      </ApolloWrapper>
    </body>
  </html>
)

export default RootLayout

```

(ProvidersWrapper contains all the providers used in the app such as Redux, etc. It is used as a client component)

**Comment by phryneas** [comment]
Could you please also share the code that calls `useSuspenseQuery`?

**Comment by IvaanTorres** [comment]
Yes, of course.

#### Screen code using useSuspenseQuery:
```ts
'use client'

/* eslint-disable implicit-arrow-linebreak */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable react/react-in-jsx-scope */

import { gql, useQuery, useSuspenseQuery } from '@apollo/client'
import Image from 'next/image'
import { FIND_CATEGORY, FIND_PRODUCT } from '../shared/services/Product'

const Home = () => {
  // TODO: Fix this for the build process
  const { data, error } = useSuspenseQuery<any>(FIND_PRODUCT, {
    variables: { id: '1' },
  })
  // const { data, loading } = useQuery(FIND_PRODUCT, {
  //   variables: { id: '1' },
  // })

  return (
    <main>
      <p>{data.product.name}</p>
    </main>
  )
}

export default Home

```

#### Query
```ts
export const FIND_PRODUCT = gql`
query Find ($id: ID!){
  product (id: $id){
    id
    name
  }
}
`
```

**Comment by phryneas** [comment]
Isn't that error expected in that case? 
This query doesn't seem to match your server - and when the server returns with an error, all SSR could do here is prerender an error page. 
If you don't have an `error.jsx/tsx` in place and no other ErrorBoundary in place, SSR would fail in this case.

**Comment by IvaanTorres** [comment]
I've got it. You were right. I didn't realize that the build process uses the .env.production instead of .env.development so I was using the production server when building, which is not as updated as the development one (as you said, that query is not setted in production).

Thanks though and sorry for the inconvenience. I close the issue.

**Comment by phryneas** [comment]
I'm gonna hit close :) Have a great day!
