### ISSUE TITLE
Resolving error message details via link leaks data to apollo

### ISSUE THREAD

**Issue by simhnna** [apollographql/apollo-client#11544]
https://github.com/apollographql/apollo-client/commit/f8c0b965d49fb7d802371bb9cc3cb0b60cf05e5d was implemented to reduce bundle size which I guess is a valid point and all is good since the unwrapping happens client side in the browser. What's not acceptable is having a "survey" endpoint that receives the complete url with all the data included.

Now my only option is to try to [disable](https://github.com/apollographql/apollo-client/issues/11260#issuecomment-1740656477) that again.

![Screenshot 2024-01-31 090155](https://github.com/apollographql/apollo-client/assets/33220646/3ac756cf-39d7-4791-b10e-f4948b9f566b)
![Screenshot 2024-01-31 090223](https://github.com/apollographql/apollo-client/assets/33220646/9ad3d11e-32a1-439b-be61-764108e626eb)
![Screenshot 2024-01-31 090238](https://github.com/apollographql/apollo-client/assets/33220646/8aad3a5e-0568-472f-b48c-e65e1e3068cd)

**Comment by simhnna** [comment]
The proposed fix is sort of working. Now I get this error (not the actual error on console)
```
ERROR TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at console.warn (<anonymous>)
    at invariant.js:35:27
    at Function.warn (invariantWrappers.js:19:12)
    at warnAboutDataLoss (writeToStore.js:397:37)
    at writeToStore.js:74:25
    at Array.forEach (<anonymous>)
    at writeToStore.js:71:42
    at Map.forEach (<anonymous>)
    at StoreWriter.writeToStore (writeToStore.js:46:30)
```
because `arguments` includes the actual data as objects
```json
{
  "0": "Cache data may be lost when replacing the %s field of a %s object.\n\nThis could cause additional (usually avoidable) network requests to fetch data that were otherwise cached.\n\nTo address this problem (which is not a bug in Apollo Client), %sdefine a custom merge function for the %s field, so InMemoryCache can safely merge these objects:\n\n  existing: %s\n  incoming: %s\n\nFor more information about these options, please refer to the documentation:\n\n  * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers\n  * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects\n",
  "1": "solutionRepo",
  "2": "InstallationStatus",
  "3": "either ensure all objects of type SolutionRepo have an ID or a custom merge function, or ",
  "4": "InstallationStatus.solutionRepo",
  "5": {
    "__typename": "SolutionRepo",
    "platformVersion": "...",
    "accountNumber": "..."
  },
  "6": { "__typename": "SolutionRepo", "accountNumber": "..." }
}

```

**Comment by bignimbus** [comment]
Thanks @simhnna for bringing this to our attention!  We are looking into it now 🙏🏻

**Comment by bignimbus** [comment]
Hi again @simhnna, thanks for your patience!  Regarding the “object to primitive value” problem: can you try the latest version?  We recently shipped a patch in 3.9.1 that should address this issue.  See https://github.com/apollographql/apollo-client/pull/11516 for more information.

Thanks again for pointing out that the URL hash property is included in that call to the documentation feedback survey, that was not intentional.  Our docs team has removed the script and survey from the website as of 2024-01-31.

I’ll close this for now but please feel free to DM me at `@jeff.auriemma` on Discord or email me at `jeff[.]auriemma[at]apollographql[.]com` with any follow-up questions!
