### ISSUE TITLE
bad string formatting when constructing error - "Cannot convert object to primitive value"

### ISSUE THREAD

**Issue by andreimatei** [apollographql/apollo-client#11640]
### Issue Description

I think there's a bug on some code path that's trying to construct an error. Looks similar too what was fixed in #11516, but I'm running 3.9.5 which should have that fix.
I see:
```
index.ts:97 Uncaught (in promise) ApolloError: Cannot convert object to primitive value
    at new ApolloError2 (index.ts:97:5)
    at Object.error (QueryManager.ts:353:48)
    at notifySubscription (module.js:137:18)
    at onNotify (module.js:176:3)
    at SubscriptionObserver2.error (module.js:229:5)
    at asyncMap.ts:45:28
```

The underlying error returned by the server is `the requested element is null which the schema does not allow`.

The problem seems to only happen in Chrome, not Firefox.

---

I've tried recording with `replay`, but I've failed to get recordings using the chromium backend. If needed, I'll try harder.

### Link to Reproduction

N/A

### `@apollo/client` version

3.9.5

**Comment by jerelmiller** [comment]
Hey @andreimatei 👋 

I'm going to close this in favor of #11639 since this looks like a duplicate 🙂
