### ISSUE TITLE
with vite ssr "TypeError: Cannot read properties of undefined (reading 'isRequired')"

### ISSUE THREAD

**Issue by veeramarni** [apollographql/apollo-client#11665]
### Issue Description

```
TypeError: Cannot read properties of undefined (reading 'isRequired')
    at /node_modules/@apollo/src/react/components/Query.tsx:32:26
    at async instantiateModule (file:///vite/dist/node/chunks/dep-G-px366b.js:54758:9)
```
Prop-types should be imported correctly in order to fix this issue 

```
import { __rest } from "tslib";
import * as PropTypes from "prop-types"; <----- to import PropTypes from 'prop-types'
import { useQuery } from "../hooks/index.js";
```

### Link to Reproduction

na

### `@apollo/client` version

3.9.6

**Comment by veeramarni** [comment]
i stopped using `@apollo/client/react/components`
