### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by lucianlature** [apollographql/apollo-client#1292]
Are self signed certificates supported?...If yes, where can I add that information and what format?

**Actual outcome:**
```
{ Error
    at new ApolloError (/Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/errors/ApolloError.js:30:23)
    at /Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/core/QueryManager.js:165:39
    at /Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/core/QueryManager.js:634:25
    at Array.forEach (native)
    at /Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/core/QueryManager.js:631:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (/Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/core/QueryManager.js:628:42)
    at QueryManager.broadcastNewStore (/Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/core/QueryManager.js:63:14)
    at /Users/codelinks/Projects/sitemanager-react/node_modules/apollo-client/src/ApolloClient.js:31:44
    at Object.dispatch (/Users/codelinks/Projects/sitemanager-react/node_modules/redux/lib/applyMiddleware.js:45:18)
  graphQLErrors: [],
  networkError:
   { Error
       at ClientRequest.<anonymous> (/Users/codelinks/Projects/sitemanager-react/node_modules/node-fetch/index.js:133:11)
       at emitOne (events.js:96:13)
       at ClientRequest.emit (events.js:189:7)
       at TLSSocket.socketErrorListener (_http_client.js:358:9)
       at emitOne (events.js:96:13)
       at TLSSocket.emit (events.js:189:7)
       at emitErrorNT (net.js:1280:8)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9)
     name: 'FetchError',
     message: 'request to https://localhost:1337/graphql failed, reason: self signed certificate',
     type: 'system',
     errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
     code: 'DEPTH_ZERO_SELF_SIGNED_CERT' },
  message: 'Network error: request to https://localhost:1337/graphql failed, reason: self signed certificate',
  extraInfo: undefined }
```
**How to reproduce the issue:**
Use `https` instead of `http`.
```
// Create our apollo client.
  const apolloClient = new ApolloClient({
    ssrMode: true,
    // Remember that this is the interface the SSR server will use to connect to the
    // API server, so we need to ensure it isn't firewalled, etc
    networkInterface: createNetworkInterface({
      uri: `**https**://${config.host}:${config.port}/graphql`,
      opts: {
        credentials: 'same-origin',
        // transfer request headers to networkInterface so that they're accessible to proxy server
        // Addresses this issue: https://github.com/matthew-andrews/isomorphic-fetch/issues/83
        headers: request.headers,
      },
    }),
  })
```

**Comment by calebmer** [comment]
This seems like an issue in your `fetch` implementation and not `apollo-client`. What `fetch` polyfill are you using? (I’m assuming you’re in Node.js because `ssrMode` is on 😊)

**Comment by helfer** [comment]
Yeah, this is definitely not something Apollo can handle for you.

**Comment by Esemesek** [comment]
For anybody who still struggles with this issue - just use `Agent`. Alternatively you might just ignore cert with option `rejectUnauthorized: false` in `Agent`.

```javascript
import * as Fs from 'fs';
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { Agent } from 'https';
import gql from 'graphql-tag';

const agent = new Agent({
  ca: Fs.readFileSync(<string>process.env.CERT_PATH),
});

const networkInterface = createNetworkInterface(<any>{
  uri: <string>process.env.DISCOVERY_PATH,
  opts: {
    agent,
  },
});

const client = new ApolloClient({ networkInterface });

export default client;
```
