### ISSUE TITLE
Update meteor apollo-client newest failed when build

### ISSUE THREAD

**Issue by lungkuteo** [apollographql/apollo-client#1454]
When build to server error. How to fix it? Thank you!

```
TypeError: Cannot use 'in' operator to search for 'default' in Symbol(observable)
at /opt/version/testtms3/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:8:29
at graphqlAnywhere (/opt/version/testtms3/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2:65)
at Object.<anonymous> (/opt/version/testtms3/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:5:2)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function._load (/root/.nvm/versions/node/v4.6.0/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```

**Comment by helfer** [comment]
@lungkuteo this looks to be an issue that's not related to apollo-client (nobody else has observed it), so I'm afraid we can't be of much help debugging it.
