### ISSUE TITLE
New bug in 1.x?

### ISSUE THREAD

**Issue by idibidiart** [apollographql/apollo-client#1655]
hi 

this was working fine in pre-1.0 Apollo Client 

```
const menuQuery = gql`query {
  menu {
    entrees {
      _id
      itemDescription
      itemPrice
      tags
      sides {
        _id
        itemDescription
        tags
      }
      upsells {
        _id
        itemDescription
        itemPrice
        tags
      }
    }
    sides {
      _id
      itemDescription
      itemPrice
      tags
    }
    appetizers {
      _id
      itemDescription
      itemPrice
      tags
    }
    deserts {
      _id
      itemDescription
      itemPrice
      tags
    }
    drinks {
      _id
      itemDescription
      itemPrice
      tags
    }
  }
}`

const observableMenuQuery = client.watchQuery({fetchPolicy: 'network-only', query: menuQuery, pollInterval: 1000 })
observableMenuQuery.subscribe({
  next: ({ data }) => displayLiveResults(data, "menu")
})
```

I updated from `forceFetch: true` to fetchPolicy

Getting this error now, which wasn't happening in pre-1.0 version of Apollo Client

> apollo.umd.js:2201 Unhandled error Network error: Cannot read property 'Symbol(id)' of null Error: Network error: Cannot read property 'Symbol(id)' of null
    at new ApolloError (http://localhost:3030/bundle.js:2022:28)
    at http://localhost:3030/bundle.js:2941:44
    at http://localhost:3030/bundle.js:3299:25
    at Array.forEach (native)
    at http://localhost:3030/bundle.js:3296:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (http://localhost:3030/bundle.js:3293:42)
    at Array.<anonymous> (http://localhost:3030/bundle.js:2675:23)
    at dispatch (http://localhost:3030/bundle.js:7684:19)
    at http://localhost:3030/bundle.js:3478:30

The error in Console points to where I inserted "HERE --->" in the Apollo Client code:
```
ApolloClient.prototype.initStore = function () {
        var _this = this;
        if (this.store) {
            return;
        }
        if (this.reduxRootSelector) {
            throw new Error('Cannot initialize the store because "reduxRootSelector" is provided. ' +
                'reduxRootSelector should only be used when the store is created outside of the client. ' +
                'This may lead to unexpected results when querying the store internally. ' +
                "Please remove that option from ApolloClient constructor.");
        }
        this.setStore(createApolloStore({
            reduxRootKey: DEFAULT_REDUX_ROOT_KEY,
            initialState: this.initialState,
            config: this.reducerConfig,
            logger: function (store) { return function (next) { return function (action) {
  **HERE ---->**              var result = next(action);
                if (_this.devToolsHookCb) {
                    _this.devToolsHookCb({
                        action: action,
                        state: _this.queryManager.getApolloState(),
                        dataWithOptimisticResults: _this.queryManager.getDataWithOptimisticResults(),
                    });
                }
                return result;
            }; }; },
        }));
    };
```

**Comment by helfer** [comment]
Hi @idibidiart, would you be able to provide a reproduction for this? You can use react-apollo-error-template.

**Comment by idibidiart** [comment]
@helfer 

resolved by making these upgrades:

```
-    "apollo-client": "^1.0.4",
+    "apollo-client": "^1.2.0",
```

```
-    "graphql": "^0.9.3",
+    "graphql": "^0.9.6",
```

It was probably something to do with apollo-client and now it's fixed, so closing for now. Sorry, would have loved to reproduce but dealing with a deadline.
