### ISSUE TITLE
Running introspection query with apollo-client results in RangeError: maximum call stack size exceeded

### ISSUE THREAD

**Issue by lunedis** [apollographql/apollo-client#1717]
**Intended outcome:**

Running the graqhql introspection query with apollo-client. It should return the server's schema in JSON format.

```
import { parse, introspectionQuery} from 'graphql';
const query = parse(introspectionQuery);
client.query({query})
      .then(...)
      .catch(...);
```

**Actual outcome:**

```
RangeError: Maximum call stack size exceeded
    at cloneDeep (D:\Users\###\Documents\EVE\teddie\teddie-client\node_modules\apollo-client\util\cloneDeep.…:1)
    at cloneDeep (D:\Users\###\Documents\EVE\teddie\teddie-client\node_modules\apollo-client\util\cloneDeep.…:9)
    at cloneDeep (D:\Users\###\Documents\EVE\teddie\teddie-client\node_modules\apollo-client\util\cloneDeep.…:9)
    at cloneDeep (D:\Users\###\Documents\EVE\teddie\teddie-client\node_modules\apollo-client\util\cloneDeep.…:9)
...
```
(goes one for quite some lines)

**Comment**

Replacing the `client.query` code with `networkInterface.query` (not using all the fancy apollo features) works.

**Comment by helfer** [comment]
Hi @lunedis. :wave: I looked at the code for `cloneDeep` in Apollo Client, but I couldn't find an obvious reason why there would be an infinite recursion. Could you provide us with a GitHub repo that I can clone and then simply run `npm install && npm test` to reproduce the issue? Thanks in advance!

**Comment by helfer** [comment]
Actually, never mind, I think I figured out what is going on. If you're using `parse` from graphql, that will result in an object with circular references, which gets cloned when typenames are added (so if you initialize the client with `addTypename: false` you won't have the issue). If you use the `gql` tag, that's not the case because it doesn't include those circular references.

We should probably make our `cloneDeep` ignore circular references. I'd be happy to accept and merge a PR in that direction.

Finally, I just wanted to point out that I don't think Apollo Client is the right tool if you simply want to execute a query against a server and get the result. For that it makes much more sense to use the network interface directly, as you have also done, it seems 👍

**Comment by miclill** [comment]
Here is how lodash solves this problem:
https://github.com/lodash/lodash/blob/master/.internal/baseClone.js#L198

**Comment by syrusakbary** [comment]
Also having this same issue

```
RangeError: Maximum call stack size exceeded
    at cloneDeep (apollo.umd.js:1276)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
    at cloneDeep (apollo.umd.js:1284)
```.

Any idea when this could be fixed?
We got this triggered in a very special edge-case.

**Comment by seeden** [comment]
I have same problem with all queries via react-apollo.
I can simulate it very easily. Try to turn off your server during the query and you will see frozen browser and after one/few minutes a lot of errors.

**Comment by yannickschuchmann** [comment]
I can confirm what @seeden says. If server is not available react-apollo goes crazy firing`APOLLO_QUERY_INIT`and `APOLLO_QUERY_STOP` which ends up in an app crash on react-native.

**Comment by volkanunsal** [comment]
Would be great to have a solution for this. `addTypename: false ` trick doesn't work for me.

**Comment by KaroseLiu** [comment]
@seeden how to solve the problem, add the 'addTypename: false' not work.

**Comment by seeden** [comment]
I did not solve it. I have this issue still in my project

**Comment by seeden** [comment]
@jbaxleyiii can you reopen this issue?

I am not able to download introspection with latest apollo-client

```js
import 'isomorphic-fetch';
import { parse, introspectionQuery } from 'graphql';
import { InMemoryCache } from 'apollo-cache-inmemory';
import ApolloClient from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { graphql } from '../config/client';

const link = new HttpLink({
  uri: graphql.url,
  credentials: 'same-origin',
});
const cache = new InMemoryCache({});

const client = new ApolloClient({
  link,
  cache,
});

const query = parse(introspectionQuery);

client
  .query({ query })
  .then((result) => {
    console.log(JSON.stringify(result, null, '  '));
  })
  .catch((err) => {
    console.error(err);
  });
```

I will always get

```
RangeError: Maximum call stack size exceeded
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:1:26)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
    at cloneDeep (/Users/seeden/Documents/git/quizana-ui/node_modules/apollo-utilities/lib/util/cloneDeep.js:9:34)
```

**Comment by FezVrasta** [comment]
I'm experiencing the same, would you consider a PR that replaces the custom `cloneDeep` with the standalone version from Lodash?

**Comment by drew24** [comment]
Having this issue as well, would be much appreciated if a solution was given 

addTypename: false

Did not work for me
@helfer

**Comment by seeden** [comment]
addTypename: false is really bad idea because apollo needs to have it. I am looking different solution.

**Comment by thachp** [comment]
I'm still able to reproduce.

├─┬ apollo-client-preset@1.0.8
│ ├─┬ apollo-cache-inmemory@1.1.7
│ │ ├─┬ apollo-cache@1.1.2
│ │ │ └── apollo-utilities@1.0.6
│ │ ├── apollo-utilities@1.0.6
│ │ └─┬ graphql-anywhere@4.1.3
│ │   └── apollo-utilities@1.0.6
│ ├─┬ apollo-client@2.2.2
│ │ ├── @types/async@2.0.47
│ │ ├─┬ apollo-link-dedup@1.0.5
│ │ │ └── apollo-link@1.0.7
│ │ ├── apollo-utilities@1.0.6
│ │ └── zen-observable@0.7.1
│ ├── apollo-link@1.0.7
│ └─┬ apollo-link-http@1.3.2
│   └── apollo-link@1.0.7
├─┬ graphql@0.11.7
│ └── iterall@1.1.3
└── graphql-tag@2.6.1

@jbaxleyiii can you reopen this issue?

**Comment by peisenmann** [comment]
Still reproduceable
```
import 'isomorphic-fetch'

import {parse} from 'graphql/language/parser'
import {introspectionQuery} from 'graphql/utilities/introspectionQuery'

import {ApolloClient} from 'apollo-client'
import {createHttpLink} from 'apollo-link-http'
import {InMemoryCache} from 'apollo-cache-inmemory'

const GRAPHQL_URL = 'http://localhost:8000/graphql'


const query = parse(introspectionQuery)
const link = createHttpLink({uri: GRAPHQL_URL})
const cache = new InMemoryCache({addTypename: true})

const client = new ApolloClient({link, cache})

client.query({ query }).then((result) => {
  console.log(JSON.stringify(result, null, '  '))
}).catch((err) => console.error(err))
```

**Comment by josepmorey** [comment]
any solution?? We have same issue...

**Comment by slycoder** [comment]
As pointed out above, this is happening because `parse` creates an object with circular references.  These references are only in the location fields of the resulting object so I don't think they're actually needed.  So you can try:

```
parse(your_query, { noLocation: true })
```

and see if that works for you.

**Comment by kibin** [comment]
@slycoder thanks! Your solution helped

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/3881 should help address this - thanks!
