### ISSUE TITLE
GraphQL error: No operation named ""

### ISSUE THREAD

**Issue by leowmjw** [apollographql/apollo-client#1760]
Was trying out the Apollo Client for the most basic of examples (from README) to get data from Github API but have been hitting a strange error.

**Intended outcome:**
- Data from Github API

**Actual outcome:**
No data, error instead:
```
proxyConsole.js:56 Error: GraphQL error: No operation named ""
    at new ApolloError (http://localhost:3000/static/js/bundle.js:60113:28)
    at http://localhost:3000/static/js/bundle.js:62408:41
    at http://localhost:3000/static/js/bundle.js:62845:25
    at Array.forEach (native)
    at http://localhost:3000/static/js/bundle.js:62842:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (http://localhost:3000/static/js/bundle.js:62839:42)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:62205:23)
    at dispatch (http://localhost:3000/static/js/bundle.js:61742:19)
    at http://localhost:3000/static/js/bundle.js:62056:30
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:60224:16)
    at http://localhost:3000/static/js/bundle.js:62783:29
    at <anonymous>
```

**How to reproduce the issue:**
Code; I used:
```
// networkInterface has Github Personal Bearer Token for authentication/authorization
const apollo_client = new ApolloClient({
    networkInterface,
})

apollo_client.query({
    
    query: gql`{
        viewer {
            avatarUrl
        }
    }`,

}).then(data => console.log(data)).catch(error => console.error(error))

```

Raw data sent over the wire:
```
{"query":"{\n  viewer {\n    avatarUrl\n    __typename\n  }\n}\n","operationName":""}
```

Have tried to put operationName in but same result:
```
apollo_client.query({
    
    query: gql`{
        viewer {
            avatarUrl
        }
    }`,
    operationName: 'Query1'

}).then(data => console.log(data)).catch(error => console.error(error))

```

I found out I need to manipulate the operationName directly to set it to null to get things working:
```
networkInterface.use([{

    applyMiddleware(req, next) {

        if (!req.options.headers) {
            req.options.headers = {}
        }
        const token = "abcdef"
        req.options.headers.authorization = token ? `Bearer ${token}` : null

        req.request.variables = {}
        req.request.operationName = null

        next()
    }

}])

```

Should operationName be set to null by default instead of "" if no value was passed in? And how to set operationName correctly (is it really needed to be manipulated in the middleware)?

Hope some guidance can be provided.  Thanks!

**Comment by stubailo** [comment]
That's interesting! The GitHub API is the only thing that has ever tripped up on this.

Our `getOperationName` function returns `""` when the operation is not named: https://github.com/apollographql/apollo-client/blob/57bdecd90aabe3af7ba548b0a38b98d06aa302dd/src/queries/getFromAST.ts#L62

Looks like the GitHub API might be expecting `null` in the case of an anonymous query. I think a very simple change to the line above to make the default value `null` instead of `''` might fix it.

If you like, you can send a PR with that change!

In the meanwhile, the best workaround is probably, in the same place you have it:

```js
req.request.operationName = req.request.operationName === '' ? null : req.request.operationName;
```

Unfortunately, the HTTP request format for GraphQL is not actually specified, or we wouldn't have to worry about things like this :[

**Comment by leowmjw** [comment]
Thanks @stubailo for the tips, I did the below change (total TS newbie) and tried to compile:
```
export function getOperationName(doc: DocumentNode): string | null {
  let res: string | null = null;
  doc.definitions.forEach((definition) => {
..
```

but encountered the following scary output -- not sure how to fix and where the rabbit hole will end 🐰 :
```
> apollo-client@1.4.0 compile /Users/leow/Desktop/PROJECTS/APOLLO/apollo-client
> tsc

src/core/ObservableQuery.ts(415,40): error TS2345: Argument of type '{ type: "APOLLO_UPDATE_QUERY_RESULT"; newResult: any; variables: { [key: string]: any; } | undefi...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_UPDATE_QUERY_RESULT"; newResult: any; variables: { [key: string]: any; } | undefi...' is not assignable to type 'UpdateQueryResultAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(285,25): error TS2345: Argument of type '{ type: "APOLLO_MUTATION_INIT"; mutationString: string; mutation: DocumentNode; variables: Object...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_MUTATION_INIT"; mutationString: string; mutation: DocumentNode; variables: Object...' is not assignable to type 'MutationInitAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(316,31): error TS2345: Argument of type '{ type: "APOLLO_MUTATION_RESULT"; result: ExecutionResult; mutationId: string; document: Document...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_MUTATION_RESULT"; result: ExecutionResult; mutationId: string; document: Document...' is not assignable to type 'MutationResultAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(419,25): error TS2345: Argument of type '{ type: "APOLLO_QUERY_INIT"; queryString: string; document: DocumentNode; operationName: string |...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_QUERY_INIT"; queryString: string; document: DocumentNode; operationName: string |...' is not assignable to type 'QueryInitAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(441,27): error TS2345: Argument of type '{ type: "APOLLO_QUERY_RESULT_CLIENT"; result: { data: any; }; variables: { [key: string]: any; };...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_QUERY_RESULT_CLIENT"; result: { data: any; }; variables: { [key: string]: any; };...' is not assignable to type 'QueryResultClientAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(863,11): error TS2322: Type '{ query: DocumentNode; variables: ({ [key: string]: any; } & undefined) | ({ [key: string]: any; ...' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
src/core/QueryManager.ts(887,33): error TS2345: Argument of type '{ type: "APOLLO_SUBSCRIPTION_RESULT"; document: DocumentNode; operationName: string | null; resul...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_SUBSCRIPTION_RESULT"; document: DocumentNode; operationName: string | null; resul...' is not assignable to type 'SubscriptionResultAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/core/QueryManager.ts(1063,11): error TS2322: Type '{ query: DocumentNode; variables: { [key: string]: any; } | undefined; operationName: string | nu...' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
src/core/QueryManager.ts(1078,31): error TS2345: Argument of type '{ type: "APOLLO_QUERY_RESULT"; document: DocumentNode; operationName: string | null; result: Exec...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_QUERY_RESULT"; document: DocumentNode; operationName: string | null; result: Exec...' is not assignable to type 'QueryResultAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
src/data/proxy.ts(242,25): error TS2345: Argument of type '{ type: "APOLLO_WRITE"; writes: { rootId: string; result: any; document: DocumentNode; operationN...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_WRITE"; writes: { rootId: string; result: any; document: DocumentNode; operationN...' is not assignable to type 'WriteAction'.
    Types of property 'writes' are incompatible.
      Type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to type 'DataWrite[]'.
        Type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to type 'DataWrite'.
          Types of property 'operationName' are incompatible.
            Type 'string | null' is not assignable to type 'string'.
              Type 'null' is not assignable to type 'string'.
src/data/proxy.ts(271,25): error TS2345: Argument of type '{ type: "APOLLO_WRITE"; writes: { rootId: string; result: any; document: DocumentNode; operationN...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_WRITE"; writes: { rootId: string; result: any; document: DocumentNode; operationN...' is not assignable to type 'WriteAction'.
    Types of property 'writes' are incompatible.
      Type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to type 'DataWrite[]'.
        Type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to type 'DataWrite'.
          Types of property 'operationName' are incompatible.
            Type 'string | null' is not assignable to type 'string'.
              Type 'null' is not assignable to type 'string'.
src/data/proxy.ts(410,21): error TS2345: Argument of type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to parameter of type 'DataWrite'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.
src/data/proxy.ts(439,21): error TS2345: Argument of type '{ rootId: string; result: any; document: DocumentNode; operationName: string | null; variables: O...' is not assignable to parameter of type 'DataWrite'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.
src/data/store.ts(180,91): error TS2345: Argument of type '{ mutationResult: ExecutionResult; queryName: string | null; queryVariables: Object; }' is not assignable to parameter of type '{ mutationResult: Object; queryName: Object; queryVariables: Object; }'.
  Types of property 'queryName' are incompatible.
    Type 'string | null' is not assignable to type 'Object'.
      Type 'null' is not assignable to type 'Object'.
test/deduplicator.ts(20,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(26,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(55,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(97,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(103,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(133,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/deduplicator.ts(139,11): error TS2322: Type '{ query: DocumentNode; variables: { x: string; }; operationName: string | null; }' is not assignable to type 'Request'.
  Types of property 'operationName' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
test/store.ts(177,20): error TS2345: Argument of type '{ type: "APOLLO_QUERY_INIT"; queryId: string; queryString: string; document: any; operationName: ...' is not assignable to parameter of type 'ApolloAction'.
  Type '{ type: "APOLLO_QUERY_INIT"; queryId: string; queryString: string; document: any; operationName: ...' is not assignable to type 'QueryInitAction'.
    Types of property 'operationName' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! apollo-client@1.4.0 compile: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the apollo-client@1.4.0 compile script.
```

**Comment by stubailo** [comment]
Oh I think that's because all of our redux actions include `operationName` and specify that it's a `string`. So all of those will have to change to `string | null` as well.

**Comment by baldurh** [comment]
Just started getting this error this morning using the Shopify Storefront API.

**Comment by stubailo** [comment]
That's odd - I wonder why people are just starting to hit this. Perhaps graphql ruby changed the way it accepts requests.

**Comment by helfer** [comment]
Fixing this as soon as possible.
