### ISSUE TITLE
apollo-boost with fetch

### ISSUE THREAD

**Issue by prateekrastogi** [apollographql/apollo-client#3193]
@peggyrayzis  Since, fetch is often required with apollo client, would it not be better to also include isomorphic-unfetch with this package too?

**Comment by peggyrayzis** [comment]
Hi @prateekrastogi! `apollo-link-http` (which is included in `apollo-boost`) uses the environment's native fetch by default. If you would like to configure fetch, you should [manually create your Apollo Client](https://www.apollographql.com/docs/react/advanced/boost-migration.html) instead of using `apollo-boost`.

**Comment by prateekrastogi** [comment]
@peggyrayzis  While trying to run this [next.js example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) , if we remove global fetch in the[ init file](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/initApollo.js), I am getting the error which indicates that the fetch in apollo-link-http might not be as context aware about environment as it should be.

Error: 
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
    at Object.checkFetcher (C:\Code\Starters\next.js\examples\with-apollo\node_modules\apollo-link-http-common\src\index.ts:175:11)
    at checkFetcher (C:\Code\Starters\next.js\examples\with-apollo\node_modules\apollo-link-http\src\httpLink.ts:44:3)
    at new HttpLink (C:\Code\Starters\next.js\examples\with-apollo\node_modules\apollo-link-http\src\httpLink.ts:234:11)
    at create (C:\Code\Starters\next.js\examples\with-apollo\lib\initApollo.js:11:11)
    at create (C:\Code\Starters\next.js\examples\with-apollo\lib\initApollo.js:23:12)
    at Function.initApollo (C:\Code\Starters\next.js\examples\with-apollo\lib\withData.js:33:22)
    at tryCatch (C:\Code\Starters\next.js\examples\with-apollo\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Code\Starters\next.js\examples\with-apollo\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Code\Starters\next.js\examples\with-apollo\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Code\Starters\next.js\examples\with-apollo\.next\dist\bundles\pages\index.js:666:191)
    at C:\Code\Starters\next.js\examples\with-apollo\.next\dist\bundles\pages\index.js:666:437
    at new Promise (<anonymous>)
    at Function.<anonymous> (C:\Code\Starters\next.js\examples\with-apollo\.next\dist\bundles\pages\index.js:666:99)
    at Function.getInitialProps (C:\Code\Starters\next.js\examples\with-apollo\lib\withData.js:13:3)
    at _callee$ (C:\Code\Starters\next.js\examples\with-apollo\node_modules\next\dist\lib\utils.js:36:30)
    at tryCatch (C:\Code\Starters\next.js\examples\with-apollo\node_modules\regenerator-runtime\runtime.js:62:40)

**Comment by peggyrayzis** [comment]
`apollo-boost` doesn't support SSR currently. I'm not sure why the maintainers of that example opted to use `apollo-boost` in that example, but I'll have to talk to them about changing it.

**Comment by prateekrastogi** [comment]
Thanks. Btw, I added apollo-boost in that example to minimize the dependency clutter and maintenance issues arising in real world projects as a result of importing multiple apollo related dependencies.
