### ISSUE TITLE
ApolloError throws an UnhandledPromiseRejectionWarning when the GraphQL response contains an error

### ISSUE THREAD

**Issue by sleyland** [apollographql/apollo-client#3476]
**Intended outcome:**
The `data.error` prop should be populated with the error when GraphQL returns a 200 http status code with an embedded error as part of the response.

*Apollo Client Configuration* - see "how to reproduce the issue"

*React Component*
```
// @flow

import React from 'react'
import { graphql } from 'react-apollo'
import type { ApolloError } from 'react-apollo'
import Loadable from 'react-loadable'
import { Redirect } from 'react-router-dom'
import type { Match } from 'react-router-dom'
import { branch, compose, renderComponent } from 'recompose'
import ErrorPage from 'components/templates/ErrorPage/ErrorPage'
import withErrorBoundary from 'containers/HOCs/ErrorBoundary/withErrorBoundary'
import { GET_PAGE_BY_NAVIGATION_PATH_QUERY } from 'gql/Page/queries'

const IndexTemplateLoadable = Loadable({
  loader: () => import('./IndexTemplate'),
  loading: () => null,
})

type Props = {
  pageByNavigationPathQuery: {
    error: ?ApolloError,
    loading: boolean,
    page: ?Page,
  },
  match: Match,
}

const enhance = compose(
  withErrorBoundary(),
  graphql(GET_PAGE_BY_NAVIGATION_PATH_QUERY, {
    name: 'pageByNavigationPathQuery',
    options: props => ({
      variables: {
        brand: "brand",
        path: props.match.url,
        render: "render",
      },
    }),
  }),
  branch(
    ({ pageByNavigationPathQuery }: Props) =>
      pageByNavigationPathQuery && pageByNavigationPathQuery.error,
    renderComponent(() => <ErrorPage status="404" />)
  )
)

export default enhance(IndexTemplateLoadable)
```

*`gql/Page/queries.js`*
```
// @flow

import gql from 'graphql-tag'

export const GET_PAGE_BY_NAVIGATION_PATH_QUERY = gql`
  query pageByNavigationPath($brand: String!, $path: String!, $render: String!) {
    page: pageByNavigationPath(brand: $brand, path: $path, render: $render) {
      id
    }
  }
`
```

**Actual outcome:**
The `data.error` prop is not populated, and instead an unhandled exception is thrown within `ApolloError`.

```
(node:12369) UnhandledPromiseRejectionWarning: Error: GraphQL error: couldn't fetch page, brand[brand], render[render], path[/unknown]. Err: rpc error: code = Internal desc = couldn't fetch page
    at new ApolloError (/Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:121:28)
    at /Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:1187:41
    at /Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:1620:17
    at Array.forEach (<anonymous>)
    at /Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:1619:18
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:1614:22)
    at Object.next (/Users/<userid>/workspace/<project>/node_modules/apollo-client/bundle.umd.js:1660:31)
    at SubscriptionObserver.next (/Users/<userid>/workspace/<project>/node_modules/zen-observable/zen-observable.js:158:20)
    at /Users/<userid>/workspace/<project>/node_modules/apollo-link-dedup/lib/bundle.umd.js:54:76
```

**How to reproduce the issue:**
When using GraphiQL to replicate the same call being made by the Apollo Client, the request/response is outlined below:

*Request Payload*
```
{
  "query": "query pageByNavigationPath($brand: String!, $render: String!, $path: String!) {
    page: pageByNavigationPath(brand: $brand, path: $path, render: $render) {
      id
    }  
  }",
  "variables": {
    "brand":"brand",
    "path":"/unknown",
    "render":"render"
  },
  "operationName":"pageByNavigationPath"
}
```

*Response (HTTP status code 200)* 
```
{
  "data": {
    "page": null
  },
  "errors": [{
    "message": "couldn't fetch page, brand[brand], render[render], path[/unknown]. Err: rpc error: code = Internal desc = couldn't fetch page",
    "path": ["page"]
  }]
}
```

When attempting to diagnose the issue I added the `onError` link to the Apollo Client in order to log out the response. 

*Apollo Client Configuration*
```
import { ApolloClient } from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { onError } from 'apollo-link-error'
import { createHttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import axios from 'axios'
import { buildAxiosFetch } from 'axios-fetch'
import environment from 'config/environment/environment'

const {
  GRAPHQL_API: { URL },
} = environment

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    graphQLErrors.forEach(({ locations, message, path }) => {
      console.log(`[GraphQL error]: Message: ${message}, Location ${locations}, Path: ${path}`)
    })
  }
  if (networkError) {
    console.log(`[Network error]: ${networkError}`)
  }
})

const httpLink = createHttpLink({
  fetch: buildAxiosFetch(axios.create({})),
  uri: URL,
})

const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([errorLink, httpLink]),
  ssrMode: true,
})

export default apolloClient
```

Which logs out the following:

```
[GraphQL error]: Message: couldn't fetch page, brand[brand], render[render], path[/unknown]. Err: rpc error: code = Internal desc = couldn't fetch page, Location undefined, Path: page
```

In order to be able to move on from the error, I have had to add the `response.errors = null` as per the documentation at https://www.apollographql.com/docs/react/features/error-handling.html#network 

**Version**
- apollo-client@2.2.8
- apollo-link@1.2.2
- apollo-link-error@1.0.9
- apollo-link-http@1.5.3

**Issue Labels**

- [x] has-reproduction

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
