### ISSUE TITLE
Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by NightFury2** [apollographql/apollo-client#4030]
**Intended outcome:**
I'm trying to initialize ApolloClient using NuxtJS and get the following error

**Actual outcome:**
```
✖ error TypeError: Cannot read property 'cache' of undefined
  at module.exports../.nuxt/apollo-module.js.__webpack_exports__.default (server-bundle.js:401:44)
  at createApp (server-bundle.js:1998:193)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**How to reproduce the issue:**
```
import Vue from 'vue';
import {ApolloClient} from 'apollo-client';
import {HttpLink} from 'apollo-link-http';
import {InMemoryCache} from 'apollo-cache-inmemory';
import VueApollo from 'vue-apollo';

const httpLink = new HttpLink({
  // You should use an absolute URL here
  uri: 'https://api.stavsvet.ru/graphql',
});

// Create the apollo client
const apolloClient = new ApolloClient({
  link: httpLink,
  ssrMode: true,
  cache: new InMemoryCache(),
  connectToDevTools: true,
});

// Install the vue plugin
Vue.use(VueApollo);

// Create a provider
const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
});

// Use the provider
export default () => {
  Vue.use(VueApollo);
  Vue.mixin({
    apolloProvider,
  });
};
```

**Versions**
"vue-apollo": "^3.0.0-alpha.3",
"apollo-cache-inmemory": "^1.3.5",
 "apollo-client": "^2.4.2",
 "apollo-link": "^1.2.3",
 "apollo-link-http": "^1.5.5",
"@nuxtjs/apollo": "^4.0.0-rc2.3",
"node": "10.6.0",
 "npm": "6.4.1"
"typescript": "^3.1.3"

**Comment by volodymyrradchenko** [comment]
Have you figured out what's the problem here?

**Comment by hwillson** [comment]
Please try a recent version of @apollo/client and let us know if this issue is still happening. Thanks!
