### ISSUE TITLE
run apollo-client in node

### ISSUE THREAD

**Issue by ismaelaarab** [apollographql/apollo-client#4541]
Hi

I am trying to run apollo client in a node env but i get the following error: 

`Detailed stack trace: Invariant Violation: Invariant Violation
    at new InvariantError (/srv/node_modules/ts-invariant/lib/invariant.js:16:28)
    at new ApolloClient (/srv/node_modules/apollo-client/bundle.umd.js:2063:63)
    at Object.<anonymous> (/srv/index.js:7:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)`

**Comment by benjamn** [comment]
Make sure `process.env.NODE_ENV` (the `NODE_ENV` environment variable) is set to `"development"`, and you'll be able to see a meaningful error message. Feel free to reopen this issue when you have more information to provide (there's nothing to go on here, sorry).
