### ISSUE TITLE
TypeError: Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by kishmiryan-karlen** [apollographql/apollo-client#4588]
**Intended outcome:**
Normal start of the express application.

**Actual outcome:**
When startitng up the express application, it crashes with the following error: 

> TypeError: Cannot read property 'delete' of undefined
    at /my-app/node_modules/apollo-link-dedup/src/dedupLink.ts:66:36
    at cleanupSubscription (/my-app/node_modules/zen-observable/lib/Observable.js:90:7)
    at notifySubscription (/my-app/node_modules/zen-observable/lib/Observable.js:145:41)
    at onNotify (/my-app/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.complete (/my-app/node_modules/zen-observable/lib/Observable.js:229:7)
    at /my-app/node_modules/apollo-link-dedup/src/dedupLink.ts:51:48
    at Set.forEach (<anonymous>)
    at Object.next (/my-app/node_modules/apollo-link-dedup/src/dedupLink.ts:51:29)
    at notifySubscription (/my-app/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/my-app/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/my-app/node_modules/zen-observable/lib/Observable.js:219:7)
    at /my-app/node_modules/apollo-link-http/src/httpLink.ts:142:20
    at process._tickCallback (internal/process/next_tick.js:68:7)

**How to reproduce the issue:**
1. Create an express (node) application. 
2. Add the following Apollo packages: `apollo-client`, `apollo-cache-inmemory` and `apollo-link-http` as well as `node-fetch`
3. Create file for initating and exporting an ApolloClient instance:
_apollo.js_
```import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import fetch from 'node-fetch';

export default new ApolloClient({
  link: new HttpLink({
    uri: `http://url.to/my/apollo/server`,
    fetch,
  }),
  cache: new InMemoryCache({
    addTypename: false,
  })
});
```
4. Import and use the instance in some endpoint of express app like this:
_routes/index.js_
```
//...
router.get('/', async function(req, res, next) {
  const res = await apollo.query({
    query: `query myQuery { someField }`
  });

  res.json(res);
});
//...
```

**Temporary Solution**
The issue persists only with version `2.4.13`. So as a temporary solution I downgraded to `2.4.12` and it worked normally.

**Versions**

_System:_
-   OS: macOS 10.14.3

_Binaries:_
-   Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
-   Yarn: 1.13.0 - /usr/local/bin/yarn
-   npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm

_Browsers:_
-   Chrome: 72.0.3626.121
-   Firefox: 65.0.1
-   Safari: 12.0.3

_npmPackages:_
-   apollo-cache-inmemory: 1.4.3 => 1.4.3 
-   apollo-client: 2.4.13 => 2.4.13 
-   apollo-link-http: 1.5.11 => 1.5.11

**Comment by hwillson** [comment]
@kishmiryan-karlen Update your version of `apollo-link-dedup` to 1.0.18 (see https://github.com/apollographql/apollo-link/issues/986 for details).
