### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by shridharbhande-tudip** [apollographql/apollo-client#4723]
Hi Team,
I am a newbie to the React but I successfully ran the react and node server on local machine but when I entered `localhost:3000` I am having the following error on the terminal:

{ Invariant Violation: Invariant Violation
    at new InvariantError (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/node_modules/apollo-client/node_modules/ts-invariant/lib/invariant.js:16:28)
    at new ApolloClient (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/node_modules/apollo-client/bundle.umd.js:2063:63)
    at Module.1TCz (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:3184)
    at r (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:225)
    at Object.0 (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:1804)
    at r (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:225)
    at /home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:1059
    at Object.<anonymous> (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/stcCqSPppjru1fRbdx7s4/pages/_app.js:1:1068)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10) framesToPop: 1, name: 'Invariant Violation' }

Please provide any solution for the same ASAP.

**Comment by benjamn** [comment]
If you run the app in development mode (not production), the error message associated with the invariant will be displayed. In production, the error strings are stripped to save bundle size (and to hide potentially confusing information from users).

In order to help you diagnose the problem, we need more information than you've provided here, especially the versions of any Apollo packages you're using, and some idea about the application code that was involved. See [`CONTRIBUTING.md`](https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#reporting-bugs) for more information about reporting bugs effectively.

Please reopen this issue when you have more information!
