### ISSUE TITLE
Can't create ApolloClient instance

### ISSUE THREAD

**Issue by zhaoyi0113** [apollographql/apollo-client#4892]
Below is my code:

```
const gql = require('graphql-tag');
const ApolloClient = require('apollo-boost');

const client = new ApolloClient({
  uri: 'http://localhost:8000/graphql'
});
```
I got this error: 
```
TypeError: ApolloClient is not a constructor
    at Object.<anonymous> (/Users/graphql/apollo-demo/src/client.js:4:16)
```

The dependencies I have is:
```
"apollo-boost": "^0.3.1",
    "apollo-cache-inmemory": "^1.6.0",
    "apollo-client": "^2.6.0",
    "apollo-link-http": "^1.5.14",
    "apollo-server": "^2.5.0",
    "apollo-server-express": "^2.5.1",
    "body-parser": "^1.19.0",
    "express": "^4.17.0",
    "graphiql": "^0.13.0",
    "graphql": "^14.3.0",
    "graphql-tag": "^2.10.1",
    "graphql-tools": "^4.0.4
```

I have tried to use `const {ApolloClient} = require('apollo-boost');` to require the ApolloClient but it reports this error: `Invariant Violation: In order to initialize Apollo Client, you must specify 'link' and 'cache' properties in the options object`.

**Comment by OurMajesty** [comment]
did you try `require('apollo-boost').default`?

**Comment by zhaoyi0113** [comment]
I changed it `require('apollo-boost').default` but got below error. Do I need to define `cache` and `link` if we use `apollo-boost`? I think the reason we use `apollo-boost` is to avoid these extra configuration of `apollo-client`. 

```

/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/lib/index.js:65
        throw new ts_invariant_1.InvariantError("\nfetch is not found globally and no fetcher passed, to fix pass a fetch for\nyour environment like https://www.npmjs.com/package/" + library + ".\n\nFor example:\nimport fetch from '" + library + "';\nimport { createHttpLink } from 'apollo-link-http';\n\nconst link = createHttpLink({ uri: '/graphql', fetch: fetch });");
        ^

Invariant Violation: 
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
    at new InvariantError (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/node_modules/ts-invariant/lib/invariant.js:16:28)
    at Object.exports.checkFetcher (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/lib/index.js:65:15)
    at Object.exports.createHttpLink (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http/lib/httpLink.js:9:31)
    at new HttpLink (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http/lib/httpLink.js:140:42)
    at new DefaultClient (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-boost/lib/bundle.cjs.js:92:24)
    at Object.<anonymous> (/Users/joeyzhao/dev/graphql/apollo-demo/src/client.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

**Comment by ozanmanav** [comment]
Hi, I had the same problem. This is available in another issue. Here #4843 

It works when you downgrade to 0.3.1 and can you try it that way?

**Comment by zhaoyi0113** [comment]
It am using 0.3.1 already: `"apollo-boost": "^0.3.1"`

**Comment by AndrewKovalenko** [comment]
try `require('apollo-boost/lib/index').default;`

**Comment by zhaoyi0113** [comment]
It doesn't work. I changed to blow code. Is `apollo-boost` ready for use? I tried the latest version and `0.3.1` but both doesn't work for a simple demo. 

```
const ApolloClient = require('apollo-boost/lib/index').default;
const client = new ApolloClient({uri: 'http://localhost:8000/graphql'});
``` 

and get this error:

```
/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/lib/index.js:65
        throw new ts_invariant_1.InvariantError("\nfetch is not found globally and no fetcher passed, to fix pass a fetch for\nyour environment like https://www.npmjs.com/package/" + library + ".\n\nFor example:\nimport fetch from '" + library + "';\nimport { createHttpLink } from 'apollo-link-http';\n\nconst link = createHttpLink({ uri: '/graphql', fetch: fetch });");
        ^

Invariant Violation:
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
    at new InvariantError (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/node_modules/ts-invariant/lib/invariant.js:16:28)
    at Object.exports.checkFetcher (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http-common/lib/index.js:65:15)
    at Object.exports.createHttpLink (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http/lib/httpLink.js:9:31)
    at new HttpLink (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-link-http/lib/httpLink.js:140:42)
    at new DefaultClient (/Users/joeyzhao/dev/graphql/apollo-demo/node_modules/apollo-boost/lib/index.js:91:24)
    at Object.<anonymous> (/Users/joeyzhao/dev/graphql/apollo-demo/src/client.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

**Comment by AndrewKovalenko** [comment]
Take a look on your stack-trace - now you have a different error. 
I suspect you are trying to use `apollo-boost` with *node* and since `fetch` API doesn't exist on *node* - your stack-trace says:

* install `node-fetch`
* `const fetch = require('node-fetch').default;`
* pass fetch to `ApolloClient` constructor
```
const client = new ApolloClient({
  uri: 'http://localhost:8000/graphql',
  fetch: fetch
});
```

**Comment by zhaoyi0113** [comment]
Thanks for pointing out this and it works now. Just curious that why I need to use `.default` on require? Is it because node? I usually import other library without `default` at the end.

**Comment by benjamn** [comment]
I'm tempted to close this as a duplicate of #4843, but it seems just different enough to remain open. We will likely fix both problems at the same time, soon!

**Comment by benjamn** [comment]
Can you try `apollo-boost@0.4.1` (just released)?

**Comment by zhaoyi0113** [comment]
I updated the version to 0.4.1 but I still need to add `.default` like `const ApolloClient = require('apollo-boost').default`. Otherwise I will get `TypeError: ApolloClient is not a constructor` error. Is 0.4.1 to fix this issue or other issues?

**Comment by AndrewKovalenko** [comment]
@zhaoyi0113 you need to add `.default` because *apollo-client* uses [ES6 modules](https://exploringjs.com/es6/ch_modules.html) and you try to reference ES6 module with [CommonJS API](https://nodejs.org/docs/latest/api/modules.html)

If you run your node app with the [support of ES6 modules](https://nodejs.org/api/esm.html) - you'll be able to use `import` and won't need to add `.default`

**Comment by AndrewKovalenko** [comment]
> #4843



> I'm tempted to close this as a duplicate of #4843, but it seems just different enough to remain open. We will likely fix both problems at the same time, soon!

I would say this is the same issue + lack of understanding about CJS/ES6 module system

**Comment by zhaoyi0113** [comment]
Oh, thanks for pointing out the issue. I close it for now.
