### ISSUE TITLE
Cannot find module apollo-client with react-testing and MockProvider

### ISSUE THREAD

**Issue by Timonzimm** [apollographql/apollo-client#6298]
I am getting an error when trying to use the `MockedProvider` to test by Apollo / NextJS web app.

My test is very basic and looks like this:

```javascript
import { MockedProvider } from '@apollo/react-testing';
import { render } from '@testing-library/react'
import Select, { ALL_CLIENTS } from '../'
...
    const { container } = render(
      <MockedProvider mocks={mocks} addTypename={false}>
        <Select />
      </MockedProvider>);
...
```

**Error:**
```
    Cannot find module 'apollo-client' from 'node_modules/@apollo/react-testing/lib/react-testing.cjs.js'

    Require stack:
      node_modules/@apollo/react-testing/lib/react-testing.cjs.js
      src/components/clients/Select/__tests__/index.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (node_modules/@apollo/react-testing/lib/react-testing.cjs.js:13:21)
```

**Versions**
```
  System:
    OS: Linux 5.6 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 76.0.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.48 => 3.0.0-beta.48 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-ssr: 3.0.0 => 3.0.0 
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    next-with-apollo: ^5.0.1 => 5.0.1
```

**Comment by TimoGruber** [comment]
You need to change your import to:
`import { MockedProvider } from '@apollo/client/testing';`

**Comment by Timonzimm** [comment]
It worked thank you, I must have missed that part in the doc or it's not updated yet.

**Comment by HugoLiconV** [comment]
I'm having a similar issue and I'm using this import `import { MockedProvider } from '@apollo/client/testing';`

`Cannot find module 'apollo-client' from 'react-testing.cjs.js'`

**Comment by alainib** [comment]
> I'm having a similar issue and I'm using this import `import { MockedProvider } from '@apollo/client/testing';`
> 
> `Cannot find module 'apollo-client' from 'react-testing.cjs.js'`

me. how do you fix it please ?
