### ISSUE TITLE
Invariant Violation: Invariant Violation: 35

### ISSUE THREAD

**Issue by RajNandigalla** [apollographql/apollo-client#6604]
```
> Build error occurred
Invariant Violation: Invariant Violation: 35 (see https://github.com/apollographql/invariant-packages)
    at new InvariantError (/Users/raj.nandigalla/workarea/nector-web/node_modules/ts-invariant/lib/invariant.js:16:28)
    at checkFetcher (/Users/raj.nandigalla/workarea/nector-web/node_modules/@apollo/client/apollo-client.cjs.js:1137:55)
    at createHttpLink (/Users/raj.nandigalla/workarea/nector-web/node_modules/@apollo/client/apollo-client.cjs.js:1241:5)
    at new HttpLink (/Users/raj.nandigalla/workarea/nector-web/node_modules/@apollo/client/apollo-client.cjs.js:1333:39)
    at createApolloClient (/Users/raj.nandigalla/workarea/nector-web/.next/server/static/ApeCkoRhWpKn0CEwuk0Ep/pages/[blog].js:2611:11)
    at initializeApollo (/Users/raj.nandigalla/workarea/nector-web/.next/server/static/ApeCkoRhWpKn0CEwuk0Ep/pages/[blog].js:2625:104)
    at getStaticPaths (/Users/raj.nandigalla/workarea/nector-web/.next/server/static/ApeCkoRhWpKn0CEwuk0Ep/pages/[blog].js:2212:61)
    at buildStaticPaths (/Users/raj.nandigalla/workarea/nector-web/node_modules/next/dist/build/utils.js:18:86)
    at Object.isPageStatic (/Users/raj.nandigalla/workarea/nector-web/node_modules/next/dist/build/utils.js:25:548)
    at execFunction (/Users/raj.nandigalla/workarea/nector-web/node_modules/jest-worker/build/workers/processChild.js:155:17) {
  type: 'InvariantError',
  framesToPop: 1,
  name: 'Invariant Violation'
}
```

The Above Error message looks sexy , but it would be nicer if it tells what went wrong instead of error code as 35 ``` Invariant Violation: Invariant Violation: 35```
where can i find the documentation for these codes ?

**Comment by benjamn** [comment]
If you tell me what version of `@apollo/client` you're using, I can show you how to find the relevant invariant in the unminified CJS bundle.

**Comment by JoviDeCroock** [comment]
This seems to stem from this line https://www.runpkg.com/?@apollo/client@3.0.1/apollo-client.cjs.js#1137 which is consistent with your error report `apollo-client.cjs.js:1137:55` and is due to 

```
"fetch\" has not been found globally and no fetcher has been configured. To fix this, install a fetch package (like https://www.npmjs.com/package/cross-fetch), instantiate the fetcher, and pass it into your HttpLink constructor. For example:\n\nimport fetch from 'cross-fetch';\nimport { ApolloClient, HttpLink } from '@apollo/client';\nconst client = new ApolloClient({\n  link: new HttpLink({ uri: '/graphql', fetch })\n});\n    
```

**Comment by RajNandigalla** [comment]
> If you tell me what version of `@apollo/client` you're using, I can show you how to find the relevant invariant in the unminified CJS bundle.

@benjamn i have the updated the Query

**Comment by RajNandigalla** [comment]
> This seems to stem from this line https://www.runpkg.com/?@apollo/client@3.0.1/apollo-client.cjs.js#1137 which is consistent with your error report `apollo-client.cjs.js:1137:55` and is due to
> 
> ```
> "fetch\" has not been found globally and no fetcher has been configured. To fix this, install a fetch package (like https://www.npmjs.com/package/cross-fetch), instantiate the fetcher, and pass it into your HttpLink constructor. For example:\n\nimport fetch from 'cross-fetch';\nimport { ApolloClient, HttpLink } from '@apollo/client';\nconst client = new ApolloClient({\n  link: new HttpLink({ uri: '/graphql', fetch })\n});\n    
> ```

Its working in the development , only causing issue for Prod build
@JoviDeCroock

**Comment by JoviDeCroock** [comment]
@RajNandigalla that's odd, so when you run your prod build (in the browser) it can't find fetch anymore?

**Comment by RajNandigalla** [comment]
@JoviDeCroock Im using Next.js 
SSR works fine , Static Site Generation (SSG) is failing 
I was using apollo/client version - 3.0.0-rc.11, i got VariantError Code 13,
after i upgraded to Release Version 3.0 im getting ErrorCode 35

**Comment by JoviDeCroock** [comment]
Yes you'll need to provide a `fetcher` for SSG to work since `fetch` isn't defined in a node-environment

**Comment by RajNandigalla** [comment]
yeah it worked thanks [Refer](https://github.com/apollographql/apollo-client/issues/6604#issuecomment-658859411)
