### ISSUE TITLE
Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by icco** [apollographql/apollo-client#6765]
**Intended outcome:**

I expect to see no error.

**Actual outcome:**

I'm upgrading my blog to apollo 3.0 on Next w/ auth from Auth0. I'm getting the following error, which from reading code seems to be related to Apollo raising a networking error.

![Screen Shot 2020-08-02 at 21 38 04](https://user-images.githubusercontent.com/20201/89138127-879eb000-d508-11ea-958e-8f9782700844.png)

Nothing seems to be in the console, but here's a dump of it.
[localhost-1596418187932.log](https://github.com/apollographql/apollo-client/files/5013418/localhost-1596418187932.log)

**How to reproduce the issue:**

I haven't figured out what the root cause is to reproduce. https://github.com/icco/writing/pull/237/files is my code where I'm migrating to the updated API.

**Versions**

```
$ npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 2.424s

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.48
    Firefox: 71.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.1 => 3.1.1
    apollo-link-persisted-queries: ^0.2.2 => 0.2.2
```

**Comment by icco** [comment]
Full dump of the error stack trace:

```
ApolloError: Expected signal to be an instanceof AbortSignal
    at new ApolloError (/Users/nat/Projects/writing/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /Users/nat/Projects/writing/node_modules/@apollo/client/core/core.cjs.js:1403:19
    at /Users/nat/Projects/writing/node_modules/@apollo/client/utilities/utilities.cjs.js:921:69
    at new Promise (<anonymous>)
    at Object.error (/Users/nat/Projects/writing/node_modules/@apollo/client/utilities/utilities.cjs.js:921:21)
    at notifySubscription (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:240:7)
    at /Users/nat/Projects/writing/node_modules/@apollo/client/utilities/utilities.cjs.js:909:68
    at Array.forEach (<anonymous>) {
  graphQLErrors: [],
  networkError: TypeError: Expected signal to be an instanceof AbortSignal
      at new Request (/Users/nat/Projects/writing/node_modules/next/dist/compiled/node-fetch/index.js:1:144524)
      at /Users/nat/Projects/writing/node_modules/next/dist/compiled/node-fetch/index.js:1:146996
      at new Promise (<anonymous>)
      at fetch (/Users/nat/Projects/writing/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /Users/nat/Projects/writing/node_modules/@apollo/client/link/http/http.cjs.js:232:13
      at new Subscription (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:197:34)
      at Observable.subscribe (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:279:14)
      at /Users/nat/Projects/writing/node_modules/apollo-link-persisted-queries/lib/bundle.umd.js:155:47
      at new Subscription (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:197:34)
      at Observable.subscribe (/Users/nat/Projects/writing/node_modules/zen-observable/lib/Observable.js:279:14),
  message: 'Expected signal to be an instanceof AbortSignal',
  extraInfo: undefined
}
```

**Comment by brandonbaraban** [comment]
I am also getting this error, please help!

**Comment by brandonbaraban** [comment]
@icco There seems to be an issue with using ApolloClient in tandem with [@auth0/auth0-react](https://github.com/auth0/auth0-react). I got the error to go away by using [@auth0/nextjs-auth0](https://github.com/auth0/nextjs-auth0) instead.

**Comment by icco** [comment]
I'm only seeing this error when using apollo in nextjs's get static functions. But unclear if it's due to auth0 or apollo or nextjs.

I thought it was a big with the fetch included with nextjs but removed that and didn't solve the issue.

**Comment by brandonbaraban** [comment]
Yeah, I was only seeing it in getServerSideProps and played around with fetch but using @auth0/nextjs-auth0 was the only thing that made the error go away 😅. Don't really understand why though to be completely honest.

**Comment by meds** [comment]
can confirm I'm seeing this exact issue, not a huge fan of this issue because the next's specific auth0 doesn't support the hooks from the react version

**Comment by icco** [comment]
So I removed auth0 and I'm pretty sure this is coming from  inside apollo. https://github.com/node-fetch/node-fetch/issues/784 could be the root issue...

**Comment by icco** [comment]
```
function client() {
  return new ApolloClient({
    ssrMode: true,
    link: new HttpLink({ uri: GRAPHQL_ORIGIN }),
    cache: new InMemoryCache(),
  });
}
```

In nextjs page
```
export async function getStaticPaths() {
  const result = await client().query({
    query: gql`
      query postIDs($offset: Int!, $perpage: Int!) {
        posts(input: { limit: $perpage, offset: $offset }) {
          id
        }
      }
    `,
    variables: {
      offset: 0,
      perpage: 2000,
    },
  });

  return {
    paths: result["data"]["posts"].map(function (d) {
      return { params: { pid: d.id } };
    }),
    fallback: true,
    revalidate: 1,
  };
}
```

**Comment by icco** [comment]
Might be that the root cause is https://github.com/vercel/next.js/issues/18044. Lots of versions of node-fetch and cross-fetch in my yarn.lock

**Comment by mihaildu** [comment]
Hey guys, I had the same issue trying to use auth0-react with next.js and apollo client. This is not an apollo client issue. 

As I understand it next.js will prefetch apollo queries using node-fetch (e.g. if you fetch data in  `getServerSideProps`). auth0-react package is using auth0-spa-js package in the back, which is using AbortController polyfills here https://github.com/auth0/auth0-spa-js/blob/master/src/index.ts#L10

From abortcontroller-polyfill package it seems you need to patch node-fetch with `abortableFetch` https://github.com/mo/abortcontroller-polyfill#using-it-on-nodejs
Not sure exactly why you need to do this, but doing so seems to fix the issue. I just assume it messes up with AbortController and AbortSignal in a way that [isAbortSignal](https://github.com/node-fetch/node-fetch/blob/v2.6.1/src/request.js#L36) will fail.

Patching the global.fetch in the next app seems to get rid of this error (for example in `app.js`):
```
import fetch from 'node-fetch';
import { abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';

global.fetch = abortableFetch(fetch).fetch;
```

**Comment by ghidoras** [comment]
> Hey guys, I had the same issue trying to use auth0-react with next.js and apollo client. This is not an apollo client issue.
> 
> As I understand it next.js will prefetch apollo queries using node-fetch (e.g. if you fetch data in `getServerSideProps`). auth0-react package is using auth0-spa-js package in the back, which is using AbortController polyfills here https://github.com/auth0/auth0-spa-js/blob/master/src/index.ts#L10
> 
> From abortcontroller-polyfill package it seems you need to patch node-fetch with `abortableFetch` https://github.com/mo/abortcontroller-polyfill#using-it-on-nodejs
> Not sure exactly why you need to do this, but doing so seems to fix the issue. I just assume it messes up with AbortController and AbortSignal in a way that [isAbortSignal](https://github.com/node-fetch/node-fetch/blob/v2.6.1/src/request.js#L36) will fail.
> 
> Patching the global.fetch in the next app seems to get rid of this error (for example in `app.js`):
> 
> ```
> import fetch from 'node-fetch';
> import { abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
> 
> global.fetch = abortableFetch(fetch).fetch;
> ```

that fixed the issue for me. thanks 👍

**Comment by jcuffney** [comment]
where would this code block go?  in `pages/_app.js`?


```
import fetch from 'node-fetch';
import { abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';

global.fetch = abortableFetch(fetch).fetch;
```

**Comment by ghidoras** [comment]
> @mihaildu where would that snippit go? in `pages/_app.js`? Where do you add polyfill's?
> 
> ```
> import fetch from 'node-fetch';
> import { abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
> 
> global.fetch = abortableFetch(fetch).fetch;
> ```

add that in pages/_document.tsx
```
import Document, { Html, Head, Main, NextScript } from "next/document";
import fetch from 'node-fetch';
import { abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
global.fetch = abortableFetch(fetch).fetch;

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="robots" content="index, follow" />
        <meta key="googlebot" name="googlebot" content="index,follow" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="keywords" content="tableau extensions, data visualization, extensions, tableau" />
      </Head>
      <body className="flex flex-col">
        <header id="page-head-container" className="sticky top-0 w-full z-30">
          <div id="banner-container" />
          <div id="header-container" />
        </header>
        <Main />
        <NextScript />
      </body>
      </Html>
    );
  }
}

export default MyDocument;

```

**Comment by aoropeza** [comment]
I got the same error and any advise here worked for me, I had to move to another graphql client :(

**Comment by bk52** [comment]
> I got the same error and any advise here worked for me, I had to movedto another graphql client :(

I found [this solution](https://github.com/reduxjs/redux-toolkit/issues/1240#issuecomment-886187893) and it works for me on Vercel

**Comment by RishikeshDarandale** [comment]
@icco , Is your problem solved with removal of `auth0-react` ? I am also facing the same issue with react-app (not next.js) with apollo client 2.6.

**Comment by cfalzone** [comment]
So FWIW, updating from node v14 to v16 fixed this error for me.

**Comment by bignimbus** [comment]
Thanks all, I'm going to close this issue as it seems there are workarounds and some upstream dependencies that may make this not actionable for the team here.  We really appreciate all the idea-sharing!
