### ISSUE TITLE
NPM Registry problem: '@wry/equality@^0.2.0' is not in the npm registry. - CRITIC

### ISSUE THREAD

**Issue by MihaiSandor** [apollographql/apollo-client#6787]
OS: Ubuntu 20.04
NodeJS Version: v14.7.0
NPM Version: 6.14.7

$ npm install @apollo/client
$ yarn add  @apollo/client

Error from npm is the same with error from yarn.
Couldn't find package "@wry/context@^0.5.2" required by "@apollo/client@^3.0.2" on the "npm" registry.

$ curl -v https://registry.npmjs.org/@wry%2fequality
 {"error":"Not found"}

**Comment by Drogbi** [comment]
Same issue.

`verbose 3.025188565 Error: Couldn't find package "@wry/equality@^0.2.0" required by "@apollo/client@^3.1.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Couldn't find package "@wry/equality@^0.2.0" required by "@apollo/client@^3.1.2" on the "npm" registry.
`

**Comment by eDubrovsky** [comment]
Same issue!

**Comment by middric** [comment]
NPM Registry issue: https://github.com/npm/cli/issues/1626

**Comment by rinatsafin** [comment]
same problem

**Comment by rinatsafin** [comment]
I think fixed?

**Comment by rost21** [comment]
> I think fixed?

Fixed

**Comment by MihaiSandor** [comment]
Fixed!
