### ISSUE TITLE
TypeError: data.QueryData is not a constructor when testing with React Testing Library

### ISSUE THREAD

**Issue by LovingGarlic** [apollographql/apollo-client#7546]
**Intended outcome:**
Run unit tests on React components that use useQuery, useMutation etc.

**Actual outcome:**
When running tests, the throw the following error:
`TypeError: data.QueryData is not a constructor`
The stack trace points to:
```
at useBaseQuery (node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js:13:9)
at useQuery (node_modules/@apollo/client/react/hooks/useQuery.js:3:12)
at ConversationPreview (src/UserApp/components/Messages/Components/ConversationPreview.js:87:68)
```

**How to reproduce the issue:**
ConversationPreview.js:
```
import { gql, useQuery } from '@apollo/client';

export const PARTICIPANTS_QUERY = gql`
  query ParticipantsInConversation($id: ID!) {
    getAllConversationParticipantsByConversationId(args: { conversationId: $id, paginationArgs: { first: 5 } }) {
      edges {
        node {
          id
          user {
            fullName
            firstName
            lastName
            id
            profileImage {
              src
            }
          }
          lastReadAt
        }
      }
    }
  }
`;

const ConversationPreview = ({ conversation, user }) => {
  const { loading: participantsLoading, data: participantsData } = useQuery(PARTICIPANTS_QUERY, {
    variables: { id: conversation.id },
  });

// Some other stuff then render...

);
```

ConversationPreview.test.js:
```
import { MockedProvider } from '@apollo/client/testing';
import { createMuiTheme, ThemeProvider } from '@material-ui/core';
import { createMount } from '@material-ui/core/test-utils';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import toJson from 'enzyme-to-json';
import ConversationPreview, { PARTICIPANTS_QUERY, LAST_MESSAGE_IN_CONVERSATION_QUERY } from '../ConversationPreview';

describe('ConversationPreview', () => {
  const theme = createMuiTheme();
  const conversation = {
    id: '1',
  };
  const user = {
    id: 999,
  };
  const mocks = [
    {
      request: {
        query: PARTICIPANTS_QUERY,
        variables: {
          id: '1',
        },
      },
      result: {
        data: {
          getAllConversationParticipantsByConversationId: {
            edges: [
              {
                node: {
                  id: '987',
                  user: {
                    fullName: 'Other Part',
                    firstName: 'Other',
                    lastName: 'Part',
                    id: '123',
                    profileImage: {
                      src: null,
                    },
                  },
                  lastReadAt: '2020-12-20T10:36:42',
                },
              },
              {
                node: {
                  id: '9876',
                  user: {
                    fullName: 'Test User',
                    firstName: 'Test',
                    lastName: 'User',
                    id: '999',
                    profileImage: {
                      src: null,
                    },
                  },
                  lastReadAt: '2020-12-19T10:36:42',
                },
              },
            ],
          },
        },
      },
    },
    {
      request: {
        query: LAST_MESSAGE_IN_CONVERSATION_QUERY,
        variables: {
          conversationId: '2',
        },
      },
      result: {
        data: {
          getAllConversationMessagesByConversationId: {
            edges: [
              {
                node: {
                  author: {
                    user: {
                      firstName: 'Other',
                      id: '123',
                    },
                  },
                  body: 'This is a test message',
                  createdAt: '2020-12-20T10:36:42',
                },
              },
            ],
          },
        },
      },
    },
  ];
  let mount;

  beforeEach(() => {
    Enzyme.configure({ adapter: new Adapter() });
    mount = createMount();
  });

  afterEach(() => {
    mount.cleanUp();
  });

  it('should render correctly', () => {
    const component = mount(
      <MockedProvider mocks={mocks} addTypename={false}>
        <ThemeProvider theme={theme}>
          <ConversationPreview conversation={conversation} user={user} />
        </ThemeProvider>
      </MockedProvider>
    );
    expect(toJson(component)).toMatchSnapshot();
  });
});
```

I've tried a few different things including removing the `ThemeProvider` component thinking that might be interfering somehow but that didn't do anything.

**Versions**
npx: installed 1 in 1.339s

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.6

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

**Comment by LovingGarlic** [comment]
For anyone who might stumble across this, my dependency tree was out of sync. Running `npm update @apollo/client graphql graphql-tag` fixed it.
