### ISSUE TITLE
Can't use MockedProvider with Enzyme and ts-jest

### ISSUE THREAD

**Issue by delucca** [apollographql/apollo-client#7680]
**Intended outcome:**
I would like to write a simple test, where I can trigger a mutation in my component. I've added more detailed information in the `How to reproduce the issue` section, but it is important to note that I'm using `ts-jest` (since my project is using Typescript) and `enzyme` to write my tests. Also, my app uses `Recoil` as a state management library.

**Actual outcome:**
After executing the `mount` command of `Enzyme` I got the following error:
```
 FAIL  src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.spec.tsx (5.157 s)
  component interactions
    ✕ can delete a key result comment from our local state (75 ms)

  ● component interactions › can delete a key result comment from our local state

    Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.

      20 | }: KeyResultSectionTimelineCardCommentProperties) => {
      21 |   const removeEntryFromTimeline = useSetRecoilState(removeTimelineEntry(data?.keyResultId))
    > 22 |   const [deleteKeyResultComment] = useMutation(queries.DELETE_KEY_RESULT_COMMENT, {
         |                                    ^
      23 |     onCompleted: () => removeEntryFromTimeline(data),
      24 |   })
      25 |

      at new InvariantError (node_modules/ts-invariant/lib/invariant.esm.js:13:28)
      at Object.invariant (node_modules/ts-invariant/lib/invariant.esm.js:25:15)
      at MutationData.Object.<anonymous>.OperationData.refreshClient (node_modules/@apollo/client/react/data/OperationData.js:29:75)
      at MutationData.Object.<anonymous>.MutationData.execute (node_modules/@apollo/client/react/data/MutationData.js:38:59)
      at Object.useMutation (node_modules/@apollo/client/react/hooks/useMutation.js:25:25)
      at KeyResultSectionTimelineCardComment (src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx:22:36)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17482:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18596:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:488:26)
      at node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:37
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at wrapAct (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:13)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:474:16)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:115:16)
      at Object.mount (node_modules/enzyme/src/mount.js:10:10)
      at Object.<anonymous> (src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.spec.tsx:9:28)

  console.error
    Error: Uncaught [Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.]
        at reportException (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
        at invokeEventListeners (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:22157:12) Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
        at new InvariantError (/home/delucca/Code/delucca/execution-mode/node_modules/ts-invariant/lib/invariant.esm.js:13:28)
        at Object.invariant (/home/delucca/Code/delucca/execution-mode/node_modules/ts-invariant/lib/invariant.esm.js:25:15)
        at MutationData.Object.<anonymous>.OperationData.refreshClient (/home/delucca/Code/delucca/execution-mode/node_modules/@apollo/client/react/data/OperationData.js:29:75)
        at MutationData.Object.<anonymous>.MutationData.execute (/home/delucca/Code/delucca/execution-mode/node_modules/@apollo/client/react/data/MutationData.js:38:59)
        at Object.useMutation (/home/delucca/Code/delucca/execution-mode/node_modules/@apollo/client/react/hooks/useMutation.js:25:25)
        at KeyResultSectionTimelineCardComment (/home/delucca/Code/delucca/execution-mode/src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.tsx:22:36)
        at renderWithHooks (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
        at mountIndeterminateComponent (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:17482:13)
        at beginWork (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:18596:16)
        at HTMLUnknownElement.callCallback (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at HTMLUnknownElement.callTheUserObjectsOperation (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
        at invokeEventListeners (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/home/delucca/Code/delucca/execution-mode/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
        at workLoopSync (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:21188:7)
        at updateContainer (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:24373:3)
        at /home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:24758:7
        at unbatchedUpdates (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:24757:5)
        at Object.render (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:24840:10)
        at fn (/home/delucca/Code/delucca/execution-mode/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:488:26)
        at /home/delucca/Code/delucca/execution-mode/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:37
        at batchedUpdates$1 (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
        at Object.act (/home/delucca/Code/delucca/execution-mode/node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
        at wrapAct (/home/delucca/Code/delucca/execution-mode/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:13)
        at Object.render (/home/delucca/Code/delucca/execution-mode/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:474:16)
        at new ReactWrapper (/home/delucca/Code/delucca/execution-mode/node_modules/enzyme/src/ReactWrapper.js:115:16)
        at Object.mount (/home/delucca/Code/delucca/execution-mode/node_modules/enzyme/src/mount.js:10:10)
        at Object.<anonymous> (/home/delucca/Code/delucca/execution-mode/src/components/KeyResult/Single/Sections/Timeline/Cards/Comment/comment.spec.tsx:9:28)
        at Object.asyncJestTest (/home/delucca/Code/delucca/execution-mode/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at /home/delucca/Code/delucca/execution-mode/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/delucca/Code/delucca/execution-mode/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/delucca/Code/delucca/execution-mode/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (node:internal/process/task_queues:93:5) {
      framesToPop: 1
    }

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)

  console.error
    The above error occurred in the <KeyResultSectionTimelineCardComment> component:
        in KeyResultSectionTimelineCardComment
        in RecoilRoot (created by WrapperComponent)
        in WrapperComponent

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.728 s, estimated 6 s
Ran all test suites matching /cards\/comment/i.
``` 

**How to reproduce the issue:**
Since it is a pretty complex environment, I'm going to explain the underlying architecture of that component.

I'm using Recoil to manage state, so I need to initialize that component inside a `RecoilRoot` (I've plenty of tests that does the same, without any issue). Also, I'm using `ts-jest` to run my tests. I don't know if that can affect anything, but It is a pretty stable lib that has not caused me any issues so far.

Besides those two libraries, the rest is pretty straightforward. Just a simple component.

Here is the component I'm trying to test:
```typescript
# comment.tsx
import { useMutation } from '@apollo/client'
import { Flex, SkeletonText } from '@chakra-ui/react'
import React from 'react'
import { useSetRecoilState } from 'recoil'

import ExpandableText from 'src/components/Base/ExpandableText'
import KeyResultSectionTimelineCardBase from 'src/components/KeyResult/Single/Sections/Timeline/Cards/Base'
import { KeyResultComment } from 'src/components/KeyResult/types'
import { removeTimelineEntry } from 'src/state/recoil/key-result/selectors'

import KeyResultSectionTimelineCardCommentHeader from './header'
import queries from './queries.gql'

export interface KeyResultSectionTimelineCardCommentProperties {
  data?: Partial<KeyResultComment>
}

const KeyResultSectionTimelineCardComment = ({
  data,
}: KeyResultSectionTimelineCardCommentProperties) => {
  const removeEntryFromTimeline = useSetRecoilState(removeTimelineEntry(data?.keyResultId))
  const [deleteKeyResultComment] = useMutation(queries.DELETE_KEY_RESULT_COMMENT, {
    onCompleted: () => removeEntryFromTimeline(data),
  })

  const handleDelete = async () => {
    await deleteKeyResultComment({
      variables: {
        keyResultCommentID: data?.id,
      },
    })
  }

  return (
    <KeyResultSectionTimelineCardBase policies={data?.policies} onDelete={handleDelete}>
      <Flex gridGap={4} direction="column">
        <KeyResultSectionTimelineCardCommentHeader
          fullName={data?.user?.fullName}
          picture={data?.user?.picture}
          date={new Date(data?.createdAt ?? 0)}
        />
        <SkeletonText noOfLines={4} isLoaded={Boolean(data)}>
          <ExpandableText text={data?.text ?? ''} fontSize="sm" />
        </SkeletonText>
      </Flex>
    </KeyResultSectionTimelineCardBase>
  )
}

export default KeyResultSectionTimelineCardComment
```

And this is the test file I've started to write for it:
```typescript
import React from 'react'
import enzyme from 'enzyme'
import { MockedProvider } from '@apollo/client/testing'
import KeyResultSectionTimelineCardComment from './comment'
import { RecoilRoot } from 'recoil'

describe('component interactions', () => {
  it('can delete a key result comment from our local state', () => {
    const wrapper = enzyme.mount(
      <RecoilRoot>
        <MockedProvider mocks={[]}></MockedProvider>
        <KeyResultSectionTimelineCardComment />
      </RecoilRoot>,
    )

    console.log(wrapper.debug())

    expect(true).toEqual(false)
  })
})
```

It is important to note that the same issue is happening in **all my components that use Apollo**. I can mount any component that does not use it, but as soon as a component from my app uses Apollo it starts with this issue. For those components, I'm testing them with shallow, by mocking Apollo, but I would like to run a real test too has less implementation details in my tests.

**Versions**
```
✦ ❯ npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 0.671s

  System:
    OS: Linux 5.9 Manjaro Linux
  Binaries:
    Node: 15.2.1 - ~/.nvm/versions/node/v15.2.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v15.2.1/bin/npm
  Browsers:
    Firefox: 85.0
  npmPackages:
    @apollo/client: ^3.2.9 => 3.3.8
```

**Comment by afreix-bricks** [comment]
`MockedProvider` should wrap your component like so: `<MockedProvider mocks={[]}><KeyResultSectionTimelineCardComment /></MockedProvider>`

**Comment by benjamn** [comment]
I second @afreix-bricks's recommendation. Closing for now, but let us know if that suggestion doesn't fix the problem @delucca.
