### ISSUE TITLE
Invariant Violation 9 error misfits when setting multi true in provider factory

### ISSUE THREAD

**Issue by ICanHasCrab** [apollographql/apollo-client#8388]
**Intended outcome:**
I am using an AppConfig InjectionToken to set the uri dynamically based on the environment and made a mistake by setting `multi: true` for the `ClassProvider` factory. The actual error I am receiving is caused by the instance not being initialized properly. I would like the errors to be more clarifying about what goes actually wrong as it puts you into a misleading direction.

**Actual outcome:**
InjectionToken usage with `multi: true` parameter gives an error about caching (invariant violation 9).

Console:
> Invariant Violation: Invariant Violation: 9 (see https://github.com/apollographql/invariant-packages)
    at new t (https://localhost:4200/main.js:1:610466)
    at new e (https://localhost:4200/main.js:1:419936)
    at e.createDefault (https://localhost:4200/main.js:1:426616)
    at new e (https://localhost:4200/main.js:1:426270)
    at Object.factory (https://localhost:4200/main.js:1:426982)
    at pi.hydrate (https://localhost:4200/main.js:1:104712)
    at pi.get (https://localhost:4200/main.js:1:102641)
    at yn (https://localhost:4200/main.js:1:75127)
    at Object.On (https://localhost:4200/main.js:1:75201)
    at e.ɵfac (https://localhost:4200/main.js:1:427486)

InvariantErrorCodes.js (invariant violation 9)
> To initialize Apollo Client, you must specify a 'cache' property " +
        "in the options object. \n" +
        "For more information, please visit: https://go.apollo.dev/c/docs")

**How to reproduce the issue:**
``` typescript
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { NgModule, InjectionToken } from '@angular/core';
import { InMemoryCache } from '@apollo/client/core';
import { APOLLO_OPTIONS } from 'apollo-angular';
import { HttpLink } from 'apollo-angular/http';

export let APP_CONFIG = new InjectionToken<any>('APP_CONFIG');

@NgModule({
  imports: [BrowserModule, HttpClientModule],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: (appConfig: any, httpLink: HttpLink) => {
        return {
          cache: new InMemoryCache(),
          link: httpLink.create({
            uri: appConfig.graphUrl,
          }),
        };
      },
      deps: [APP_CONFIG, HttpLink],
      multi: true // <-- With this line, invariant violation 9 is served
    },
  ],
})
export class AppModule { }
```

**Versions**
```
@angular/cli@12.0.3
@angular/core@12.0.3
@apollo/client@3.3.19
apollo-angular@2.6.0
graphql@15.5.0
typescript@4.2.4
```

**Comment by bignimbus** [comment]
Hi @ICanHasCrab 👋🏻 thanks for your patience.  This appears to be related to the `apollo-angular` project.  You may be able to find more specific guidance at https://github.com/kamilkisiela/apollo-angular.  Thanks again!
