### ISSUE TITLE
TypeError when using higher-order component

### ISSUE THREAD

**Issue by brainkim** [apollographql/apollo-client#8464]
A bug from Apollo Studio.
```
    TypeError: hoistNonReactStatics.default is not a function

      80 | `;
      81 |
    > 82 | export const OverviewSectionWithData = flowRight(
         |                                        ^
      83 |   withQueryParams(),
      84 |   graphql(queryListQuery, {
      85 |     options: ({ serviceId, filter }) => {

      at node_modules/@apollo/client/react/hoc/query-hoc.js:68:36
      at node_modules/lodash/_createFlow.js:68:42
```

**Comment by brainkim** [comment]
Probably related to 1bb182c40c320ec89be3667c8f81965328c07aeb
