### ISSUE TITLE
Invariant Violation: Expecting a parsed GraphQL document. When running test with MockedProvider

### ISSUE THREAD

**Issue by Moumene** [apollographql/apollo-client#8528]
**Intended outcome:**
I want to be able to test my Screen with query using MockedProvider, I followed the instructions [here](https://www.apollographql.com/docs/react/development-testing/testing/). But when I run my test I get an error.

Here's my query and the mock

``` javascript
export const GET_MY_INFO = gql`
  query getMyInfo {
    GetMyInfo {
      scope
      id
      email
    }
  }
`;

export const mocks = [
  {
    request: {
      query: GET_MY_INFO,
      variables: {},
    },
    result: {
      data: {
        GetMyInfo: { id: '1', scope: 'Buck', email: 'bulldog' },
      },
    },
  },
];
```

And here the test file

``` javascript
// other imports here....
import { MockedProvider } from '@apollo/client/testing';

describe('Logout', () => {
  test('should display confirmation before logout', async () => {
    const { getByText, queryByTestId } = renderWithProviders(
      <MockedProvider
        mocks={mocks}
        addTypename={false}
        defaultOptions={{
          watchQuery: { fetchPolicy: 'no-cache' },
          query: { fetchPolicy: 'no-cache' },
        }}
      >
        <HomeScreen />
      </MockedProvider>,
    );
    const logoutButton = getByText('Logout');

    act(async () => {
      await fireEvent.press(logoutButton);
    });
    await waitFor(() =>
      expect(queryByTestId('confirmation-test-id')).toBeTruthy(),
    );
  });
}

```

**Actual outcome:**

``` console
 Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql

      at new InvariantError (node_modules/ts-invariant/lib/invariant.esm.js:12:28)
      at Object.invariant (node_modules/ts-invariant/lib/invariant.esm.js:24:15)
      at checkDocument (node_modules/@apollo/client/utilities/graphql/getFromAST.js:4:93)
      at Object.removeConnectionDirectiveFromDocument (node_modules/@apollo/client/utilities/graphql/transform.js:147:67)
      at MockLink.normalizeMockedResponse (node_modules/@apollo/client/utilities/testing/mocking/mockLink.js:100:38)
      at MockLink.addMockedResponse (node_modules/@apollo/client/utilities/testing/mocking/mockLink.js:29:45)
      at node_modules/@apollo/client/utilities/testing/mocking/mockLink.js:23:23
          at Array.forEach (<anonymous>)
      at new MockLink (node_modules/@apollo/client/utilities/testing/mocking/mockLink.js:22:29)
      at new MockedProvider (node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:15:27)

```

**How to reproduce the issue:**

Create a test for a screen with a query used in it, and try to test the screen with MockedProvider following the instructions on the link above.

**Versions**

```
 System:
    OS: macOS 11.3.1
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 82.0.2
    Safari: 14.1
  npmPackages:
    @apollo/client: 3.3.13 => 3.3.13 
    apollo3-cache-persist: ^0.9.1 => 0.9.1 
```

**Comment by brainkim** [comment]
What does `<HomeScreen />` look like? You may be incorrectly passing a string into the hook call rather than a gql document.

**Comment by Moumene** [comment]
@brainkim here's my implementation of HomeScreen

``` javascript
export const HomeScreen: React.FC = () => {

  const { data, loading, error } = useGetMyInfo();

  return (
    <DsBox style={{ height: '100%' }}>
      // ...
    </DsBox>
  );
};

```

the `useGetMyInfo()` is defined like this in a separate file

``` javascript
export const GET_MY_INFO = gql`
  query getMyInfo {
    GetMyInfo {
      scope
      id
      email
    }
  }
`;

export type GetMyInfoResult = {
  id: string;
  scope: string;
  email: string;
};

export const useGetMyInfo = () => {
  return useQuery<{ GetMyInfo: GetMyInfoResult }>(GET_MY_INFO);
};
```

**Comment by brainkim** [comment]
@Moumene Thanks for tolerating my questions, and sorry to hear you’re having trouble. I’ll try to investigate this when I can; in the meantime, if you created a reproduction which caused this error to be thrown, with the error template (https://github.com/apollographql/react-apollo-error-template/blob/optimistic-mutation-and-polling/src/index.jsx) or whatever else you’re comfortable with, that would be very helpful!

**Comment by Moumene** [comment]
Hi @brainkim after trying to reproduce the issue i found an issue in my jest mocks, there was a mock for Apollo client 😅
