### ISSUE TITLE
useQuery - Bluebird warning: a promise was created in a handler, but was not returned from it

### ISSUE THREAD

**Issue by in15** [apollographql/apollo-client#8747]
**Intended outcome:**
Successful useQuery call without any warnings

**Actual outcome:**
Successful useQuery call with Bluebird warnings about a Promise without a return.

```
Warning: a promise was created in a handler at /localhost:3001/static/js/vendors~app~vendor.chunk.js:67983:38 but was not returned from it, see http://goo.gl/rRqMUw    at Function.Promise.cast (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:115043:13)    at onNewData (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:66107:25)    at Object.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:65493:17)    at notifySubscription (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377208:18)    at onNotify (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377252:3)    at SubscriptionObserver.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377301:5)    at http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:68    at Array.forEach (<anonymous>)    at iterateObserversSafely (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:25)    at ObservableQuery.push../node_modules/@apollo/client/core/ObservableQuery.js.ObservableQuery.reportResult (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:61378:95)    at Object.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:61356:23)    at http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:68    at Array.forEach (<anonymous>)    at iterateObserversSafely (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:25)    at Object.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:67814:97)    at notifySubscription (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377208:18)    at onNotify (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377252:3)    at SubscriptionObserver.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377301:5)    at http://localhost:3001/static/js/vendors~app~vendor.chunk.js:67983:38From previous event:    at Object.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:67981:66)    at notifySubscription (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377208:18)    at onNotify (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377252:3)    at SubscriptionObserver.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377301:5)    at http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:68    at Array.forEach (<anonymous>)    at iterateObserversSafely (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:68030:25)    at Object.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:67814:97)    at notifySubscription (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377208:18)    at onNotify (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377252:3)    at SubscriptionObserver.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377301:5)    at notifySubscription (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377208:18)    at onNotify (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377252:3)    at SubscriptionObserver.next (http://localhost:3001/static/js/vendors~app~vendor.chunk.js:377301:5)    at http://localhost:3001/static/js/vendors~app~vendor.chunk.js:63366:26
```

**How to reproduce the issue:**
This appears to be happening on every successful useQuery call

**Versions**
Node: 10.16.2 
apollo/client: 3.4.10

**Comment by mtoranzoskw** [comment]
Having the same issue ☝️
