### ISSUE TITLE
node.getChildTrie is not a function with NextJS on the server side

### ISSUE THREAD

**Issue by Gregoor** [apollographql/apollo-client#8864]
Hi there, unfortunately I don't have a repro for it, as we are only seeing it in production. When rendering a specific page we are getting an error and seeing this in our logs:

```ts
TypeError: node.getChildTrie is not a function
    at /app/node_modules/@wry/trie/lib/trie.js:29:65
    at Array.forEach (<anonymous>)
    at Trie.lookupArray (/app/node_modules/@wry/trie/lib/trie.js:29:17)
    at ObjectCanon.admit (/app/node_modules/@apollo/client/cache/cache.cjs.js:639:42)
    at /app/node_modules/@apollo/client/cache/cache.cjs.js:637:44
    at Array.forEach (<anonymous>)
    at ObjectCanon.admit (/app/node_modules/@apollo/client/cache/cache.cjs.js:636:33)
    at Object.assign.reset (/app/node_modules/@apollo/client/cache/cache.cjs.js:675:40)
    at StoreReader.diffQueryAgainstStore (/app/node_modules/@apollo/client/cache/cache.cjs.js:763:28)
    at InMemoryCache.diff (/app/node_modules/@apollo/client/cache/cache.cjs.js:1934:33)
```

We are using `@apollo/client` version `3.4.13`.

**Comment by benjamn** [comment]
@Gregoor What version do you see in `node_modules/@wry/trie/package.json`?

**Comment by Gregoor** [comment]
@benjamn `0.3.1`

Some more info, apparently we might be re-using the same ApolloClient for several concurent requests, which seems enough of an anti-pattern that I'd say the error lies probably in our codebase. Still maybe interesting to figure out if polluting the cache like that can be prevented.

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and found this issue.  @Gregoor do you still need support here?
