### ISSUE TITLE
TypeError: value.subscribe is not a function

### ISSUE THREAD

**Issue by afmw20** [apollographql/apollo-client#8887]
I'm trying to use BatchHttpLink to batch requests from apollo on a nextjs application using below config:

```
import fetch from 'isomorphic-unfetch';
import { ApolloProvider, ApolloClient, ApolloLink, from } from '@apollo/client'; 
import { onError } from '@apollo/client/link/error'; 
import { BatchHttpLink } from '@apollo/client/link/batch-http';

const batchHttpLink = new BatchHttpLink({
    uri: process.env.GRAPHQL_URL,
    batchMax: 5,
    batchInterval: 20,
    credentials: 'same-origin',
    fetch
});

  /**
   * to parse batch call response
   * See more https://spectrum.chat/apollo/apollo-client/batchhttplink-not-working-with-usequery-react-hooks~3eeb6635-c5a8-4b8a-a2fd-3b7fbebc5816
   */
  const parseBatchResponseMiddleware = new ApolloLink((operation, forward) =>
    forward(operation).map((data: any) => data.payload)
  );

  const errorLink = onError(({ graphQLErrors, networkError, forward, operation }) => {
    if (graphQLErrors) {
      console.warn(graphQLErrors);
    }
    if (networkError) {
      console.warn(networkError);
    }
    forward(operation);
  });

  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: from([parseBatchResponseMiddleware, errorLink, authLink.concat(batchHttpLink)]),
    cache: new InMemoryCache({
      possibleTypes: introspectionToPossibleTypes(introspectionQueryResultData)
    })
  });

```

I added parseBatchResponseMiddleware to parse the batch response. When I run app on development mode everything seems correct but as soon as I build app on prod environment it returns 500-internal server error:

```
TypeError: value.subscribe is not a function at Object.complete (/.../node_modules/@apollo/client/utilities/observables/Concast.js:57:43) at Concast.start (/.../node_modules/@apollo/client/utilities/observables/Concast.js:83:23) at new Concast (/.../node_modules/@apollo/client/utilities/observables/Concast.js:75:19) at QueryManager.getObservableFromLink (/.../node_modules/@apollo/client/core/QueryManager.js:551:35) at QueryManager.getResultsFromLink (/.../node_modules/@apollo/client/core/QueryManager.js:590:30) at resultsFromLink (/.../node_modules/@apollo/client/core/QueryManager.js:755:26) at QueryManager.fetchQueryByPolicy (/.../node_modules/@apollo/client/core/QueryManager.js:782:21) at fromVariables (/.../node_modules/@apollo/client/core/QueryManager.js:638:26) at QueryManager.fetchQueryObservable (/.../node_modules/@apollo/client/core/QueryManager.js:645:15) at QueryManager.fetchQuery (/.../node_modules/@apollo/client/core/QueryManager.js:260:21) at QueryManager.query (/.../node_modules/@apollo/client/core/QueryManager.js:345:21) at ApolloClient.query (/.../node_modules/@apollo/client/core/ApolloClient.js:133:34) at Function.Z.t.getInitialProps (/.../src/.next/server/pages/_app.js:158:151526) at Function.B.r.getInitialProps (/.../src/.next/server/pages/_app.js:158:147992)

```

Any ideas to solve this issue is highly appreciated.

**Comment by afmw20** [comment]
> That would be this line. Hmm.
> 
> https://github.com/apollographql/apollo-client/blob/684765eb52db0da94397f6a101c582cba1cef0db/src/utilities/observables/Concast.ts#L210
> 
> We can look into it!
> 
> > When I run app on development mode everything seems correct but as soon as I build app on prod environment it returns 500-internal server error
> 
> Do you have a screenshot of the network error from the network tab?


**It returns 500 error when I build and start app:**

<img width="449" alt="Screen Shot 2021-10-07 at 09 25 43" src="https://user-images.githubusercontent.com/72735755/136327705-7b21223c-f680-4229-9321-b6e01c08d651.png">

<img width="1265" alt="Screen Shot 2021-10-07 at 09 23 52" src="https://user-images.githubusercontent.com/72735755/136327628-4c7f9b29-4f9f-48fc-89f2-7a2bb504aa31.png">

**Comment by fdemian** [comment]
Hi, I'm having the same problems. 
Whenever the server returns a 400 response (or any error response, looks like), I get the same error using a custom error link. This is the code for my error link:

```
const errorLink = onError(async (props) => {
  const { graphQLErrors, networkError } = props;
  if (graphQLErrors) {
    for (let error of graphQLErrors) {
      const { message, path } = error;
      console.log(`[GraphQL error]: Message: ${message}, Path: ${path}`)
      const resCode = message.toString();
      if(resCode === "401") {
        redirectToLogout();
      }
      if(resCode === "403") {
        redirectToLogout();
      }
    }
  }
  if (networkError) {
    console.log(`[Network error]: ${networkError}`);
  }
});
```

**Comment by jerelmiller** [comment]
Hey all 👋 

I'm doing some housekeeping and I don't believe this is an issue in 4.0 anymore. We moved to RxJS in 4.0 and removed the `Concast` class because it was no longer needed.

Please see the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-4-migration) for instructions on upgrading to 4.0. If you have any other issues after upgrading, please open a new issue and we'd be happy to take a look. Thanks!
