### ISSUE TITLE
Documentation - Testing React components

### ISSUE THREAD

**Issue by Shankhara** [apollographql/apollo-client#9255]
# [Documentation examples](https://www.apollographql.com/docs/react/development-testing/testing/) cause console errors
- As I am testing a `react-native` app, I changed `<p>` to `<Text>`. These are the only modifications I found necessary.
- The second error detailed above could be caused by different use between `react` and `react-native`, if it is please tell me.
- Tests pass but display unexpected console errors
## Dog component
```jsx
import React from 'react';
import { gql, useQuery } from '@apollo/client';

// Make sure that both the query and the component are exported
export const GET_DOG_QUERY = gql`
  query GetDog($name: String) {
    dog(name: $name) {
      id
      name
      breed
    }
  }
`;

export function Dog({ name }) {
  const { loading, error, data } = useQuery(
    GET_DOG_QUERY,
    { variables: { name } }
  );
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error!</p>;

  return (
    <p>
      {data.dog.name} is a {data.dog.breed}
    </p>
  );
}
```
## Dog test
```jsx
import TestRenderer from 'react-test-renderer';
import { MockedProvider } from '@apollo/client/testing';
import { GET_DOG_QUERY, Dog } from './dog';

const mocks = [
  {
    request: {
      query: GET_DOG_QUERY,
      variables: {
        name: 'Buck',
      },
    },
    result: {
      data: {
        dog: { id: '1', name: 'Buck', breed: 'bulldog' },
      },
    },
  },
];

it('renders without error', () => {
  const component = TestRenderer.create(
    <MockedProvider mocks={mocks} addTypename={false}>
      <Dog name="Buck" />
    </MockedProvider>,
  );

  const tree = component.toJSON();
  expect(tree.children).toContain('Loading...');
});
```
### First run
```
ReferenceError: React is not defined

      21 | it('renders without error', () => {
      22 |   const component = TestRenderer.create(
    > 23 |     <MockedProvider mocks={mocks} addTypename={false}>
         |     ^
      24 |       <Dog name="Buck" />
      25 |     </MockedProvider>,
      26 |   );

      at Object.<anonymous> (__tests__/dog.test.js:23:5)
```
- Missing `import React from "react";` in `dog.test.js`
- Once missing import added run the same test again
### Second run
```
  console.error
    Warning: An update to Dog inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
      at Dog (/.../components/Dog.js:25:19)
      at ApolloProvider (/.../node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
      at MockedProvider (/.../node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)
      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:68:30)
      at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:44:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15034:9)
      at dispatchAction (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7129:9)
      at node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js:19:119
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Text [as Text] (node_modules/react-native/index.js:107:12)
      at Dog (components/Dog.js:38:52)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at updateFunctionComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8340:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9980:16)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `Dog`.
      at Dog (/.../components/Dog.js:25:19)
      at ApolloProvider (/.../node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
      at MockedProvider (/.../node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)
      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2215:7)
      at Dog (components/Dog.js:38:25)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at updateFunctionComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8340:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9980:16)

  console.error
    The above error occurred in the <Dog> component:
    
        at Dog (/.../components/Dog.js:25:19)
        at ApolloProvider (/.../node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
        at MockedProvider (/.../node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
```
- Following strictly the documentation gives this error.

## Package.json
```json
{
  "name": "...",
  "version": "...",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@apollo/client": "3.4.16",
    "@testing-library/react-native": "^9.0.0",
    "depcheck": "^1.4.2",
    "graphql": "15.7.2",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-encrypted-storage": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.16.4",
    "@react-native-community/eslint-config": "^2.0.0",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "verbose": true,
    "preset": "react-native"
  }
}
```

**Comment by hwillson** [comment]
@Shankhara code snippets in the Apollo Client documentation are intended to be used to visually understand how parts of Apollo Client itself work, not necessarily be copy/paste-able code snippets that will run out of the box. We often omit certain imports (for 3rd party libraries like React) and application config elements, for the sake of brevity. If you feel strongly that these missing elements should be included here, we'll review a PR, but please note that very few of the docs code snippets can actually be run as is.
