### ISSUE TITLE
Tests are failing when the client option isn't included in the useMutation hook

### ISSUE THREAD

**Issue by tynandebold** [apollographql/apollo-client#9264]
**Intended outcome:**

I would expect my tests to pass without having to add the `client` API option, just like they do with the `useQuery` hook, which doesn't contain the `client`.

A quick note about the code: we have a top-level `<Wrapper/>` component, where we have our `<Provider/>` wrapping everything, so the context is there.

Another note: there's no instance of `apollo-client` anywhere. I've run `npm rm apollo-client` to be sure. We're only using `@apollo/client` throughout.

**Actual outcome:**

The tests fail. Here's the stack trace:

```
Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClientApolloClient instance in via options.

      13 | const RunDetailsModal = ({ onClose, runMetadataToEdit, theme, visible }) => {
      14 |   const [valuesToUpdate, setValuesToUpdate] = useState({});
    > 15 |   const [updateRunDetails, { error }] = useMutation(UPDATE_RUN_DETAILS, {
         |                                         ^
      16 |     refetchQueries: [GET_RUN_METADATA],
      17 |   });
      18 |

      at new InvariantError (node_modules/ts-invariant/lib/invariant.esm.js:12:28)
      at Object.invariant (node_modules/ts-invariant/lib/invariant.esm.js:24:15)
      at useApolloClient (node_modules/@apollo/client/react/hooks/useApolloClient.js:7:15)
      at useMutation (node_modules/@apollo/client/react/hooks/useMutation.js:9:18)
      at RunDetailsModal (src/components/experiment-tracking/run-details-modal/index.js:15:41)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17482:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18596:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:488:26)
      at node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:37
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at wrapAct (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:13)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:474:16)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:115:16)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at Object.<anonymous> (src/components/experiment-tracking/run-details-modal/run-details-modal.test.js:19:21)

  console.error
    Error: Uncaught [Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClientApolloClient instance in via options.]
        at reportException (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
        at invokeEventListeners (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:22157:12) Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClientApolloClient instance in via options.
        at new InvariantError (/Users/tynandebold/sites/kedro-viz/node_modules/ts-invariant/lib/invariant.esm.js:12:28)
        at Object.invariant (/Users/tynandebold/sites/kedro-viz/node_modules/ts-invariant/lib/invariant.esm.js:24:15)
        at useApolloClient (/Users/tynandebold/sites/kedro-viz/node_modules/@apollo/client/react/hooks/useApolloClient.js:7:15)
        at useMutation (/Users/tynandebold/sites/kedro-viz/node_modules/@apollo/client/react/hooks/useMutation.js:9:18)
        at RunDetailsModal (/Users/tynandebold/sites/kedro-viz/src/components/experiment-tracking/run-details-modal/index.js:15:41)
        at renderWithHooks (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
        at mountIndeterminateComponent (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:17482:13)
        at beginWork (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:18596:16)
        at HTMLUnknownElement.callCallback (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at HTMLUnknownElement.callTheUserObjectsOperation (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
        at invokeEventListeners (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/tynandebold/sites/kedro-viz/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
        at workLoopSync (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:21188:7)
        at updateContainer (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:24373:3)
        at /Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:24758:7
        at unbatchedUpdates (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:24757:5)
        at Object.render (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:24840:10)
        at fn (/Users/tynandebold/sites/kedro-viz/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:488:26)
        at /Users/tynandebold/sites/kedro-viz/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:37
        at batchedUpdates$1 (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
        at Object.act (/Users/tynandebold/sites/kedro-viz/node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
        at wrapAct (/Users/tynandebold/sites/kedro-viz/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:13)
        at Object.render (/Users/tynandebold/sites/kedro-viz/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:474:16)
        at new ReactWrapper (/Users/tynandebold/sites/kedro-viz/node_modules/enzyme/src/ReactWrapper.js:115:16)
        at mount (/Users/tynandebold/sites/kedro-viz/node_modules/enzyme/src/mount.js:10:10)
        at Object.<anonymous> (/Users/tynandebold/sites/kedro-viz/src/components/experiment-tracking/run-details-modal/run-details-modal.test.js:19:21)
        at Promise.then.completed (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/utils.js:276:28)
        at new Promise (<anonymous>)
        at callAsyncCircusFn (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/utils.js:216:10)
        at _callCircusTest (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/run.js:212:40)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at _runTest (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/run.js:149:3)
        at _runTestsForDescribeBlock (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/run.js:63:9)
        at _runTestsForDescribeBlock (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/run.js:57:9)
        at run (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/run.js:25:3)
        at runAndTransformResultsToJestFormat (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
        at jestAdapter (/Users/tynandebold/sites/kedro-viz/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
        at runTestInternal (/Users/tynandebold/sites/kedro-viz/node_modules/jest-runner/build/runTest.js:380:16)
        at runTest (/Users/tynandebold/sites/kedro-viz/node_modules/jest-runner/build/runTest.js:472:34)
        at Object.worker (/Users/tynandebold/sites/kedro-viz/node_modules/jest-runner/build/testWorker.js:133:12) {
      framesToPop: 1
    }

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

**How to reproduce the issue:**

- Head over to [this branch](https://github.com/quantumblacklabs/kedro-viz/tree/feature/rename-run-and-edit-notes-behavior%23ked-2997) of the repo.
- Clone it.
- Install dependencies (`npm install`). Use Node 14.
- Remove the `client` option from the `useMutation` hook in [this file](https://github.com/quantumblacklabs/kedro-viz/blob/feature/rename-run-and-edit-notes-behavior%23ked-2997/src/components/experiment-tracking/run-details-modal/index.js).
- Run `npm run test src/components/experiment-tracking/run-details-modal/run-details-modal.test.js` in your CLI.
- The tests should fail with a similar stack trace to the one shown above.

**Versions**

```
System:
  OS: macOS 11.6
Binaries:
  Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
  npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
Browsers:
  Chrome: 96.0.4664.110
  Safari: 15.2
npmPackages:
  @apollo/client: ^3.5.6 => 3.5.6
```

**Comment by bignimbus** [comment]
Hi @tynandebold 👋🏻  thanks for your patience!  Do you still need support on this?  I tried opening those links but I think those branches have been deleted.  Happy to help narrow down what might be going on!
