### ISSUE TITLE
Can't test loading state with MockedProvider + no-cache

### ISSUE THREAD

**Issue by matart15** [apollographql/apollo-client#9387]
Summary : 

Mockprovider renders directly to `{ loading: false, error: "Not enough Mock data" }` state, if `no-cache` is specified

Component
```
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

export const ONLINE_QUERY = gql`
  query ONLINE {
    isOnline
  }
`;

export const TestComponent = () => {
  const { error: pollError, loading: pollLoading, data } = useQuery(
    ONLINE_QUERY,
    {
      fetchPolicy: 'no-cache',
    },
  );
  console.log('pollError: ', {
    pollError: !!pollError,
    pollLoading,
    data,
  });
  return null;
};
```

Test: 

```
import React from 'react';
import { act, render } from '@testing-library/react';
import * as TestComponentAll from '../TestComponent';
import { MockedProvider } from '@apollo/react-testing';
import { MemoryRouter } from 'react-router-dom';

const Online = TestComponentAll.TestComponent;

const mockObject = {
  onlineQueryMock1: {
    request: {
      query: TestComponentAll.ONLINE_QUERY,
      variables: {
        // pollInterval: 60000,
        // fetchPolicy: 'no-cache',
      },
    },
    result: {
      data: {
        isOnline: false,
      },
    },
  },
};

describe('test', () => {
  it('test', async () => {
    await act(async () => {
      render(
        <MemoryRouter>
          <MockedProvider
            mocks={[
              mockObject.onlineQueryMock1,
            ]}>
            <Online />
          </MockedProvider>
        </MemoryRouter>,
      );
    });
  });
});
```

Result
```
 PASS  __test__/TestComponents.test.tsx (11.179 s)
  test
    ✓ test (41 ms)

  console.log
    pollError:  { pollError: false, pollLoading: true, data: undefined }

      at TestComponent (src/@app/layout/MainLayout/TestComponent.tsx:20:11)

  console.log
    pollError:  { pollError: true, pollLoading: false, data: undefined }

      at TestComponent (src/@app/layout/MainLayout/TestComponent.tsx:20:11)

```

If i remove ` fetchPolicy: 'no-cache',`

Result : 
```
 PASS  __test__/TestComponents.test.tsx (11.31 s)
  test
    ✓ test (35 ms)

  console.log
    pollError:  { pollError: false, pollLoading: true, data: undefined }

      at TestComponent (src/@app/layout/MainLayout/TestComponent.tsx:20:11)

```

Maybe Related : https://github.com/apollographql/react-apollo/issues/2867

**Comment by SamRoehrich** [comment]
I think you are using `no-cache` and `poll options` incorrectly in the mock. 
No cache and poll options are not variables but a query option. You can [disable cache](https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-defaultoptions-object) at the `MockedProvider` level.

**Comment by matart15** [comment]
I see thank you. will try that
